### ISSUE TITLE
Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [sammchardy/python-binance#1001]
Using the client.get_asset_balance command results in a "Timestamp for this request is outside of the recvWindow." error. This error just started occurring today. I never had the issue before. Full error message:

```
Traceback (most recent call last):
  File "Balance and symbol checker.py", line 23, in <module>
    USDT_balance = client.get_asset_balance(asset='USDT')
  File "C:\Program Files\Python37\lib\site-packages\binance\client.py", line 1979, in get_asset_balance
    res = self.get_account(**params)
  File "C:\Program Files\Python37\lib\site-packages\binance\client.py", line 1954, in get_account
    return self._get('account', True, data=params)
  File "C:\Program Files\Python37\lib\site-packages\binance\client.py", line 365, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\binance\client.py", line 328, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\binance\client.py", line 309, in _request
    return self._handle_response(self.response)
  File "C:\Program Files\Python37\lib\site-packages\binance\client.py", line 318, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request is outside of the recvWindow.
```

**Comment by asdsadsaasd12312132** [comment]
Seems to occur when you resume your computer from sleep. You have to restart your computer to fix it.
