### ISSUE TITLE
API Withdrawal Error

### ISSUE THREAD

**Issue by tjpeterson94** [sammchardy/python-binance#1039]
Recieving error message generated from python-binance library when attempting withdrawal.  Withdrawals worked fine until the wapi->sapi upgrade:

```
>>> withdrew = client.withdraw(asset='BNB',address='XXXXX',amount=0.1,name='BNB')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpeterson/environments/test_env/lib/python3.8/site-packages/binance/client.py", line 2527, in withdraw
    return self._request_margin_api('post', 'capital/withdraw/apply', True, data=params)
  File "/home/jpeterson/environments/test_env/lib/python3.8/site-packages/binance/client.py", line 364, in _request_margin_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/jpeterson/environments/test_env/lib/python3.8/site-packages/binance/client.py", line 315, in _request
    return self._handle_response(self.response)
  File "/home/jpeterson/environments/test_env/lib/python3.8/site-packages/binance/client.py", line 324, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=100001003): Verification failed
```

**Comment by tjpeterson94** [comment]
Note: 
-Withdrawals enabled on api
-Many withdrawals done to this address through both API and manually

**Comment by dpcwee** [comment]
> Note:
> -Withdrawals enabled on api
> -Many withdrawals done to this address through both API and manually

Try to fill in the white list with the IP address of the machine from which the output is made via the API

**Comment by tjpeterson94** [comment]
IP address of machine was whitelisted under the API list still receiving same error.  Discussed with Binance API telegram group they have indicated that this error message was not generated by the Binance server.

**Comment by thinkingparticle** [comment]
what was the source of problem. I have the same issue
