### ISSUE TITLE
APIError(code=-2010): This action disabled is on this account.

### ISSUE THREAD

**Issue by Fo3nix** [sammchardy/python-binance#1120]
**Describe the bug**
>>> client.create_order(symbol="ETHUPUSDT", side=SIDE_BUY, type=ORDER_TYPE_MARKET, quantity=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Finn\AppData\Local\Programs\Python\Python310\lib\site-packages\binance\client.py", line 1385, in create_order
    return self._post('order', True, data=params)
  File "C:\Users\Finn\AppData\Local\Programs\Python\Python310\lib\site-packages\binance\client.py", line 374, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "C:\Users\Finn\AppData\Local\Programs\Python\Python310\lib\site-packages\binance\client.py", line 334, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\Finn\AppData\Local\Programs\Python\Python310\lib\site-packages\binance\client.py", line 315, in _request
    return self._handle_response(self.response)
  File "C:\Users\Finn\AppData\Local\Programs\Python\Python310\lib\site-packages\binance\client.py", line 324, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-2010): This action disabled is on this account.

**To Reproduce**
from binance.client import Client
from binance.enums import *

client = Client(api_key, secret_key)
client.create_order(symbol="ETHUPUSDT", side=SIDE_BUY, type=ORDER_TYPE_MARKET, quantity=1)

**Expected behavior**
I was trying to buy ETHUP, but it said the function was disabled. How do I enable it?

**Comment by halfelf** [comment]
This seems not an issue of this library.  Can you trade `ETHUP` on binance website?

**Comment by Fo3nix** [comment]
> 

Thanks. Unfortunately the site also won't let me trade it. It says it has something to do with jurisdiction. Probably because I live in the Netherlands then. Well thanks for replying anyway!
