### ISSUE TITLE
start_aggtrade_futures_socket always produce KeyError: 'e'

### ISSUE THREAD

**Issue by punmew** [sammchardy/python-binance#1167]
**Describe the bug**
start_aggtrade_futures_socket always failed to initiate no matter which parameters I passed. I tried other start_ functions (i.e. spot, kline) they are all working fine except aggtrade.

**To Reproduce**
import time
import json, config
from binance import ThreadedWebsocketManager
from binance.enums import FuturesType, ContractType
from binance.client import AsyncClient

api_key = config.API_KEY
api_secret = config.API_SECRET

#https://binance-docs.github.io/apidocs/futures/en/#change-log

def main():

    symbol = 'BTCUSDT'

    twm = ThreadedWebsocketManager(api_key=api_key, api_secret=api_secret)
    # start is required to initialise its internal loop
    twm.start()

    def handle_socket_message(msg):
        print(f"message type: {msg['e']}")
        print(msg)

    twm.start_aggtrade_futures_socket(callback=handle_socket_message, symbol=symbol, futures_type=FuturesType.USD_M)

    twm.join()

if __name__ == "__main__":
   main()

**Expected behavior**
The session should be initiated and start streaming.

**Environment (please complete the following information):**
 - Python version: 3.9.7
 - Virtual Env: conda
 - OS: Windows11
 - python-binance version: 1.0.15

**Logs or Additional context**
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<ThreadedApiManager.start_listener() done, defined at D:\OneDrive\OIG Tech\Tradingview_BOT\project_env\lib\site-packages\binance\threaded_stream.py:42> exception=KeyError('e')>
Traceback (most recent call last):
  File "D:\OneDrive\OIG Tech\Tradingview_BOT\project_env\lib\site-packages\binance\threaded_stream.py", line 52, in start_listener
    callback(msg)
  File "d:\OneDrive\OIG Tech\Tradingview_BOT\websocket.py", line 21, in handle_socket_message
    print(f"message type: {msg['e']}")
KeyError: 'e'

**Comment by halfelf** [comment]
Why don't you print the message first and check the content? 

Anyway the result is expected and indeed there is no key `'e'` in `msg`.
