### ISSUE TITLE
client.futures_account_balance() :API Secret required for private endpoints

### ISSUE THREAD

**Issue by allthemod** [sammchardy/python-binance#1180]
**the bug and logs**
ok i called the fuction client.futures_account_balance() and he gave me an error:
Traceback (most recent call last):
  File "C:\Users\omizr\PycharmProjects\test\main.py", line 28, in <module>
    print(client.futures_account_balance())
  File "C:\Users\omizr\.virtualenvs\test-frrPpWs3\lib\site-packages\binance\client.py", line 6055, in futures_account_balance
    return self._request_futures_api('get', 'balance', True, data=params)
  File "C:\Users\omizr\.virtualenvs\test-frrPpWs3\lib\site-packages\binance\client.py", line 339, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\omizr\.virtualenvs\test-frrPpWs3\lib\site-packages\binance\client.py", line 312, in _request
    kwargs = self._get_request_kwargs(method, signed, force_params, **kwargs)
  File "C:\Users\omizr\.virtualenvs\test-frrPpWs3\lib\site-packages\binance\client.py", line 270, in _get_request_kwargs
    kwargs['data']['signature'] = self._generate_signature(kwargs['data'])
  File "C:\Users\omizr\.virtualenvs\test-frrPpWs3\lib\site-packages\binance\client.py", line 220, in _generate_signature
    assert self.API_SECRET, "API Secret required for private endpoints"
AssertionError: API Secret required for private endpoints

**Expected behavior**
i expetcted that the fuction give me the usdt amount in binance Futures wallet

**Environment :**
 - Python version: 3.9 and 3.7
 - Virtual Env: pipnv
 - OS: windows 10
 - python-binance 1.0.16

**Comment by martines328** [comment]
![image](https://user-images.githubusercontent.com/55957474/177137995-8af5f91b-07d6-43d1-b515-18bf3c2c3503.png)
