### ISSUE TITLE
After updating to 0.6.3 - frozen importlib._bootstrap_external

### ISSUE THREAD

**Issue by jasonmellone** [sammchardy/python-binance#151]
Hi,

After uninstalling binance and reinstalling to 0.6.3 I am getting the following error:

`C:\ProgramData\Anaconda3\envs\crypto30\python.exe C:/Users/username/PycharmProjects/crypto/client_run.py
Traceback (most recent call last):
  File "C:/Users/username/PycharmProjects/crypto/client_run.py", line 1, in <module>
    import crypto.account as crypto_account
  File "C:\users\username\PycharmProjects\crypto\account.py", line 2, in <module>
    import crypto.exchange_client as exchange_client
  File "C:\users\username\PycharmProjects\crypto\exchange_client.py", line 8, in <module>
    from binance.client import Client
  File "C:\ProgramData\Anaconda3\envs\crypto30\lib\site-packages\binance\client.py", line 8, in <module>
    from .helpers import date_to_milliseconds, interval_to_milliseconds
  File "C:\ProgramData\Anaconda3\envs\crypto30\lib\site-packages\binance\helpers.py", line 3, in <module>
    import dateparser
  File "C:\ProgramData\Anaconda3\envs\crypto30\lib\site-packages\dateparser\__init__.py", line 4, in <module>
    from .date import DateDataParser
  File "C:\ProgramData\Anaconda3\envs\crypto30\lib\site-packages\dateparser\date.py", line 11, in <module>
    from dateparser.date_parser import date_parser
  File "C:\ProgramData\Anaconda3\envs\crypto30\lib\site-packages\dateparser\date_parser.py", line 10, in <module>
    from .conf import apply_settings
  File "C:\ProgramData\Anaconda3\envs\crypto30\lib\site-packages\dateparser\conf.py", line 66, in <module>
    settings = Settings()
  File "C:\ProgramData\Anaconda3\envs\crypto30\lib\site-packages\dateparser\conf.py", line 32, in __init__
    self._updateall(self._get_settings_from_yaml().items())
  File "C:\ProgramData\Anaconda3\envs\crypto30\lib\site-packages\dateparser\conf.py", line 45, in _get_settings_from_yaml
    data = get_data('data', 'settings.yaml')
  File "C:\ProgramData\Anaconda3\envs\crypto30\lib\pkgutil.py", line 634, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\PycharmProjects\\crypto\\data\\settings.yaml'

Process finished with exit code 1
`

Where `C:\\Users\\username\\PycharmProjects\\crypto\\` is my project folder.

I did not do anything outside of uninstall+reinstall. What is causing this? I am getting this when running in pycharm and command line.

**Comment by sammchardy** [comment]
Hi @jasonmellone it seems to be related to this issue

https://github.com/scrapinghub/dateparser/issues/352

It seems to be caused by having a directory called `data` in your `C:\Users\username\PycharmProjects\crypto\` directory.

The issue does reference a fix and I'll update the dateparser dependency when that is released.
