### ISSUE TITLE
'WebSocketClientProtocol' object has no attribute 'makeConnection'

### ISSUE THREAD

**Issue by LeoIannacone** [sammchardy/python-binance#198]
Hi,

I'm randomly getting this error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
    why = selectable.doWrite()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 583, in doConnect
    self._connectDone()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 612, in _connectDone
    self.protocol.makeConnection(self)
exceptions.AttributeError: 'WebSocketClientProtocol' object has no attribute 'makeConnection'

Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/binance/websockets.py", line 464, in run
    reactor.run(installSignalHandlers=False)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1255, in mainLoop
    self.doIteration(t)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 475, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 289, in connectionLost
    protocol.connectionLost(reason)
exceptions.AttributeError: 'WebSocketClientProtocol' object has no attribute 'connectionLost'
```

**Comment by ikubay** [comment]
I have the same issue, and I use Python 3. It occurs when I close the socket manager and start a new socket. The problem is not exclusive to a certain type of socket either.

**Comment by davidefiozzi** [comment]
Same here. Did you find how to solve this problem?

**Comment by jpgremm** [comment]
Same problem here, did anyone find a solution?
