### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by Klaudioz** [sammchardy/python-binance#223]
I'm getting this error constantly and like randomly. I put some print to look the place where the error is happening. Normally is after the print ("0") or print ("4.1") so I know the error happens when I'm requesting something from the API.

**Code:**

> ...
            print("0")
            dict_coin = (client.get_historical_klines(symbol_elem, client.KLINE_INTERVAL_1MINUTE, candle_request))
            print("1")
            if len(dict_coin)>0:
                print("2")
                for row in dict_coin: #OHLCV
                    del row[0:1]
                    del row[1:11]
                print("3")
                HH = float(max(dict_coin)[0])
                for elem in all_tickers:
                    if elem['s'] == symbol_elem:
                        close = float(elem['b'])
                print("4")
                dip = round(100*(HH/close - 1),2)
                # Not send the alert if the coin is already bought
                print("4.1")
                open_orders = client.get_open_orders()
                print("4.2")
                open_orders_list = []
                print("5")
                for dict in open_orders:
                    open_orders_list.append(dict['symbol'])
                ....
**Error:**

> Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file alerts.py, line 74
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

I'm very sure it's not an API limitation because I started to test this code few minutes ago after few days.
I updated the version of the pip as well.

**Comment by Klaudioz** [comment]
I'm sorry .. it was a typo .. probably I'm very tired
