### ISSUE TITLE
Error 1104

### ISSUE THREAD

**Issue by Bl4ckDoT** [sammchardy/python-binance#226]
Error (line:

binance.exceptions.BinanceAPIException: APIError(code=-1104): Not all sent parameters were read; read '0' parameter(s) but was sent '1'.

![image](https://user-images.githubusercontent.com/11063272/37935753-b85af674-3120-11e8-91d7-ac1f71319d39.png)

**Comment by tamycova** [comment]
What was the rest of the stderr?

**Comment by Bl4ckDoT** [comment]
This is pretty much the entire script. I'm only trying to create a simple GUI that has a buy and sell button to buy or sell at market price for the full amount (or close to 100%).

0.0
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\klodz\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\klodz\Desktop\Binance test.py", line 15, in MBuy
    BTCinfo = client.get_ticker(asset='BTC')
  File "C:\Users\klodz\AppData\Local\Programs\Python\Python36\lib\site-packages\binance\client.py", line 830, in get_ticker
    return self._get('ticker/24hr', data=params)
  File "C:\Users\klodz\AppData\Local\Programs\Python\Python36\lib\site-packages\binance\client.py", line 206, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\klodz\AppData\Local\Programs\Python\Python36\lib\site-packages\binance\client.py", line 180, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\klodz\AppData\Local\Programs\Python\Python36\lib\site-packages\binance\client.py", line 175, in _request
    return self._handle_response(response)
  File "C:\Users\klodz\AppData\Local\Programs\Python\Python36\lib\site-packages\binance\client.py", line 199, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-1104): Not all sent parameters were read; read '0' parameter(s) but was sent '1'.
Traceback (most recent call last):
  File "C:\Users\klodz\Desktop\Binance test.py", line 72, in <module>
    window.bind('<a>', HBuy) #binds 'a' to the HBuy function
  File "C:\Users\klodz\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1245, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "C:\Users\klodz\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1200, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: can't invoke "bind" command: application has been destroyed
[Finished in 80.8s]

**Comment by sammchardy** [comment]
Hi @Bl4ckDoT the correct parameter name for `get_ticker` is `symbol`

See here the docs here https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.get_ticker
