### ISSUE TITLE
AttributeError: 'BinanceAPIException' object has no attribute 'code'

### ISSUE THREAD

**Issue by alexanderkoumis** [sammchardy/python-binance#228]
I have a wrapper around the `Client` object that retries any call that fails and raises immediately if the exception matches a list of search strings:

```python
from time import sleep

def Retry(func, max_retries, raise_immediately_strs):

    def wrapper(*args, **kwargs):

        num_tries = 0
        while True:
            try:
                return func(*args, **kwargs)
            except Exception as exc:

                for raise_immediately_str in raise_immediately_strs:
                    try:
                        if raise_immediately_str in str(exc):
                            raise
                    except Exception:
                        raise

                if num_tries >= max_retries:
                    raise

                print('Retrying {}'.format(func.__name__))
                num_tries += 1
                sleep(0.3)

    return wrapper

class BinanceClientWrapped(object):

    def __init__(self, client, max_retries, raise_immediately_strs):
        self._client = client
        self.max_retries = max_retries
        self.raise_immediately_strs = raise_immediately_strs

    def __getattr__(self, name, *args, **kwargs):
        attr = self._client.__getattribute__(name)
        if callable(attr):
            return Retry(attr, self.max_retries, self.raise_immediately_strs)
        else:
            return attr
```
I use it like this:
```
client = Client(api_config['api_key'], api_config['api_secret'])
client = BinanceClientWrapped(client, MAX_API_RETRIES, RAISE_IMMEDIATELY_STRS)
```
This works perfectly most of the time but my program just failed with the following message:
```
  File "/home/ubuntu/a/binance_client_wrapped.py", line 15, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/a/venv/lib/python3.4/site-packages/binance/client.py", line 908, in get_orderbook_ticker
    return self._get('ticker/bookTicker', data=params, version=self.PRIVATE_API_VERSION)
  File "/home/ubuntu/a/venv/lib/python3.4/site-packages/binance/client.py", line 206, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home/ubuntu/a/venv/lib/python3.4/site-packages/binance/client.py", line 180, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/ubuntu/a/venv/lib/python3.4/site-packages/binance/client.py", line 175, in _request
    return self._handle_response(response)
  File "/home/ubuntu/a/venv/lib/python3.4/site-packages/binance/client.py", line 199, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./a.py", line 755, in <module>
    main()
  File "./a.py", line 751, in main
    update()
  File "./a.py", line 609, in update
    update_prices_buffer()
  File "./a.py", line 209, in update_prices_buffer
    for ticker in client.get_orderbook_ticker():
  File "/home/ubuntu/a/binance_client_wrapped.py", line 20, in wrapper
    if raise_immediately_str in str(exc):
  File "/home/ubuntu/a/venv/lib/python3.4/site-packages/binance/exceptions.py", line 22, in __str__
    return 'APIError(code=%s): %s' % (self.code, self.message)
AttributeError: 'BinanceAPIException' object has no attribute 'code'
```
So this occurs when I am reading the `___str___` version of the `BinanceAPIException` on line 22 of exceptions.py. The sequence goes like this:
* The client throws a `BinanceAPIException` after receiving an error message from the API
* My wrapper catches this exception, and then tries to read from the exception by doing `if raise_immediately_str in str(exc)`
* The program fails because BinanceAPIException.code is not defined

This is very strange to me because it appears from the source of `BinanceAPIException` that if it's `__init__` function is called, `self.code` will unconditionally be set:
```python

    def __init__(self, response):
        self.code = 0
        try:
            json_res = response.json()
        except ValueError:
            self.message = 'Invalid JSON error message from Binance: {}'.format(response.text)
        else:
            self.code = json_res['code']
            self.message = json_res['msg']
        self.status_code = response.status_code
        self.response = response
        self.request = getattr(response, 'request', None)
```
Anybody have any ideas how it is possible that a `BinanceAPIException` is being instantiated without setting `self.code`?

**Comment by sammchardy** [comment]
Hi @alexanderkoumis,

You're right that is a really strange error, reviewing the current code doesn't seem to indicate that the error could occur.

Can you check that you have the latest version of the library? There was an update last month that added the `self.code = 0` line

**Comment by alexanderkoumis** [comment]
The version I'm running is 0.6.6 (came from `pip3 install python-binance`). Looks like in 0.6.6 the variable is incorrectly named `self.status_code`:
```

    def __init__(self, response):
        self.status_code = 0
        try:
            json_res = response.json()
        except ValueError:
            self.message = 'Invalid JSON error message from Binance: {}'.format(response.text)
        else:
            self.code = json_res['code']
            self.message = json_res['msg']
        self.status_code = response.status_code
        self.response = response
        self.request = getattr(response, 'request', None)
```
I'll upgrade to 0.6.8, thanks.
