### ISSUE TITLE
I met a crash, and only get such a piece of log. Hope it may help.

### ISSUE THREAD

**Issue by duduzhu** [sammchardy/python-binance#25]
```
File "/usr/local/lib64/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/usr/local/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "/usr/local/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 475, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/usr/local/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 289, in connectionLost
    protocol.connectionLost(reason)
  File "/usr/local/lib64/python2.7/site-packages/twisted/protocols/tls.py", line 398, in connectionLost
    self._flushReceiveBIO()
  File "/usr/local/lib64/python2.7/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/local/lib64/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1545, in processData
    fr = self.onFrameData(payload)
  File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1639, in onFrameData
    self._onMessageFrameData(payload)
  File "/usr/local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 150, in _onMessageFrameData
    self.onMessageFrameData(payload)
  File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 601, in onMessageFrameData
    self.frame_data.append(payload)
exceptions.AttributeError: 'NoneType' object has no attribute 'append'

```

**Comment by sammchardy** [comment]
Hi @duduzhu I'm not sure I have enough information to action this. The stack trace doesn't show it hitting my code which makes it difficult to catch the error.
Have you run into it again?

**Comment by duduzhu** [comment]
I met it a few times before, but not recent days.
There is a possibility that it's due to binance sides' problem.
Don't bother, I will output more log and see if I will have it again.

**Comment by JMedon** [comment]
Hi I got the same issue

```
Unhandled Error
Traceback (most recent call last):
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1553, in processData
    fr = self.onFrameEnd()
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1674, in onFrameEnd
    self._onMessageEnd()
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 159, in _onMessageEnd
    self.onMessageEnd()
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 627, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "E:\python-binance\binance\websockets.py", line 30, in onMessage
    self.factory.callback(payload_obj)
  File "E:/python-binance/main.py", line 23, in process_m_message
    datas=msg['data']
builtins.KeyError: 'data'

Unhandled Error
Traceback (most recent call last):
  File "E:\python-binance\binance\websockets.py", line 441, in run
    reactor.run(installSignalHandlers=False)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\base.py", line 1243, in run
    self.mainLoop()
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\base.py", line 1255, in mainLoop
    self.doIteration(t)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\selectreactor.py", line 143, in doSelect
    _logrun(selectable, _drdw, selectable, method)
--- <exception caught here> ---
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\selectreactor.py", line 154, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, method=="doRead")
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\tcp.py", line 475, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\tcp.py", line 289, in connectionLost
    protocol.connectionLost(reason)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\tls.py", line 398, in connectionLost
    self._flushReceiveBIO()
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1545, in processData
    fr = self.onFrameData(payload)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1639, in onFrameData
    self._onMessageFrameData(payload)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 150, in _onMessageFrameData
    self.onMessageFrameData(payload)
  File "C:\Users\Jakub Medon\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 601, in onMessageFrameData
    self.frame_data.append(payload)
builtins.AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by JMedon** [comment]
Hi I got the same issue.
```
Unhandled Error
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1553, in processData
    fr = self.onFrameEnd()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1674, in onFrameEnd
    self._onMessageEnd()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 159, in _onMessageEnd
    self.onMessageEnd()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 627, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "E:\python-binance\binance\websockets.py", line 30, in onMessage
    self.factory.callback(payload_obj)
  File "E:/python-binance/main.py", line 23, in process_m_message
    datas=msg['data']
builtins.KeyError: 'data'

Unhandled Error
Traceback (most recent call last):
  File "E:\python-binance\binance\websockets.py", line 441, in run
    reactor.run(installSignalHandlers=False)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\base.py", line 1243, in run
    self.mainLoop()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\base.py", line 1255, in mainLoop
    self.doIteration(t)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\selectreactor.py", line 143, in doSelect
    _logrun(selectable, _drdw, selectable, method)
--- <exception caught here> ---
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\selectreactor.py", line 154, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, method=="doRead")
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\tcp.py", line 475, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\internet\tcp.py", line 289, in connectionLost
    protocol.connectionLost(reason)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\tls.py", line 398, in connectionLost
    self._flushReceiveBIO()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\twisted-17.9.0-py3.6-win-amd64.egg\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 131, in dataReceived
    self._dataReceived(data)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1175, in _dataReceived
    self.consumeData()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1187, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1545, in processData
    fr = self.onFrameData(payload)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 1639, in onFrameData
    self._onMessageFrameData(payload)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\twisted\websocket.py", line 150, in _onMessageFrameData
    self.onMessageFrameData(payload)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\autobahn\websocket\protocol.py", line 601, in onMessageFrameData
    self.frame_data.append(payload)
builtins.AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by duduzhu** [comment]
@JMedon , your root cause is clear as I quoted.
And this may happen in your callback function right? My solution is to catch possible exception in order to avoid them being throwed into python-binance. 
```
  File "E:/python-binance/main.py", line 23, in process_m_message
    datas=msg['data']
builtins.KeyError: 'data'
```
