### ISSUE TITLE
Thredpool Problem

### ISSUE THREAD

**Issue by Savadiv** [sammchardy/python-binance#265]
Greetings,

I am trying to observe every single coin on Binance. These are approx. 150 coins. To do this I want to use websockets, since its much more faster than single Client queries. To be concrete: I want to have three websockets for every coin: 1h klines, 1m klines and ticker. My problem is sadly, that when I have many coins I get an error from twisted as follows:

```
Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/Library/Python/2.7/site-packages/binance/websockets.py", line 436, in run
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 1195, in run
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 1204, in mainLoop
--- <exception caught here> ---
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
  File "/Library/Python/2.7/site-packages/twisted/internet/tcp.py", line 414, in resolveAddress
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 570, in resolve
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 271, in getHostByName
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 992, in getThreadPool
  File "/Library/Python/2.7/site-packages/twisted/internet/base.py", line 957, in _initThreadPool
    
exceptions.ImportError: cannot import name threadpool
```

Is there any workaround or solution to this? 

Thank you very much!

**Comment by dikano** [comment]
@wranai can you plz help me close one symbol stream on the multiplex socket 
i tried the bm.close_socket(conn_key) and the bm.close()
didnt work

**Comment by dikano** [comment]
@wranai 
thanks again for the reply .Im trying to automate trades based on Signals from another bot...  , so i need to constantly open new sockets on each incoming Signal, i thought it will be cleaner if i use multiplex sockets but for that i need to close the socket, append the new symbols ,than reopen it with the new list. it didnt work out well...
do you recommend opening single  trade sockets using loop iteration over the symbols without closing them ?
i cant find another way.
