### ISSUE TITLE
After a long run, websocket may encounter "listen-key does not exist"

### ISSUE THREAD

**Issue by duduzhu** [sammchardy/python-binance#28]
Binance technician replies that I should put for another listen-key.
I think this exception should be handled automatically.

```
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 1076, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/binance/websockets.py", line 295, in _keepalive_user_socket
    self._client.stream_keepalive(listenKey=self._user_listen_key)
  File "/usr/local/lib/python2.7/site-packages/binance/client.py", line 1113, in stream_keepalive
    return self._put('userDataStream', False, data=params)
  File "/usr/local/lib/python2.7/site-packages/binance/client.py", line 140, in _put
    return self._request_api('put', path, signed, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/binance/client.py", line 108, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/binance/client.py", line 103, in _request
    return self._handle_response(response)
  File "/usr/local/lib/python2.7/site-packages/binance/client.py", line 127, in _handle_response
    raise BinanceAPIException(response)
BinanceAPIException: APIError(code=-1125): This listenKey does not exist.

```

**Comment by sammchardy** [comment]
@duduzhu I've added a check on the [develop branch](https://github.com/sammchardy/python-binance/tree/develop) which regenerates the listen key and attempts a keep alive.
This now completely restarts the user socket using the same callback when it finds that error. 
Could you test and check if it's still causing you issues?

**Comment by duduzhu** [comment]
I will try.
But it happens rarely.

**Comment by sammchardy** [comment]
v0.5.0 released with code to hopefully resolve this. Have had a socket running for about 12 hours without issue. Reopen the issue if it resurfaces.
