### ISSUE TITLE
websocket unhandled error

### ISSUE THREAD

**Issue by sourbudzzz** [sammchardy/python-binance#318]
Twisted version 17.9.0

trying to run this on mac:

from binance import client, websockets
import time, threading
from binance.websockets import BinanceSocketManager

APIKEY=""
SECRET=""

bin_client = client.Client(APIKEY,SECRET)

current_time = str(int(time.time()) * 1000)
start_time = str(int(time.time() - 10 * 1) * 1000)

bin_client.get_aggregate_trades(symbol="EOSBTC", startTime=start_time, endTime=current_time)

bm = BinanceSocketManager(client)

wss = websockets.BinanceSocketManager(bin_client)

info = bin_client.get_symbol_info(symbol="EOSBTC")
min_tick = float(info['filters'][0]['tickSize'])

def process_message_book(msg):
    print msg

partial_key = bm.start_depth_socket("EOSBTC", process_message_book, depth=BinanceSocketManager.WEBSOCKET_DEPTH_20)

bm.start()

It just keeps printing out this error:

Unhandled Error
Traceback (most recent call last):
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/internet/tcp.py", line 583, in doConnect
    self._connectDone()
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/internet/tcp.py", line 597, in _connectDone
    self.protocol = self.connector.buildProtocol(self.getPeer())
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 1122, in buildProtocol
    return self.factory.buildProtocol(addr)
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/protocols/policies.py", line 171, in buildProtocol
    return self.protocol(self, self.wrappedFactory.buildProtocol(addr))
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/twisted/internet/protocol.py", line 140, in buildProtocol
    p = self.protocol()
  File "/Users/JC/PycharmProjects/projectone/venv/lib/python2.7/site-packages/binance/websockets.py", line 19, in __init__
    super().__init__()
exceptions.TypeError: super() takes at least 1 argument (0 given)

**Comment by alienatorZ** [comment]
I am getting the same error in Ubuntu with python 2.7.

**Comment by b2397** [comment]
The fix by @BNB48ClubSirIan to websocket.py resolved the error for me.
`exceptions.TypeError: super() takes at least 1 argument (0 given)`

Thanks!
