### ISSUE TITLE
Getting a ValueError

### ISSUE THREAD

**Issue by brssnj54** [sammchardy/python-binance#322]
Fixed previous mpl_finance error with a pip install "pip install mpl_finance"

Now getting a new error 

>Traceback (most recent call last):
  File "/home/brian/Desktop/Trading bot/python-binance-master/examples/RoibalBot.py", line 348, in <module>
    run()
  File "/home/brian/Desktop/Trading bot/python-binance-master/examples/RoibalBot.py", line 104, in run
    scalping_orders(coin, 1, 1)
  File "/home/brian/Desktop/Trading bot/python-binance-master/examples/RoibalBot.py", line 194, in scalping_orders
    ap, aq, bp, bq, place_ask_order, place_bid_order, spread, proj_spread, max_bid, min_ask = visualize_market_depth(wait, tot_time, coin)
  File "/home/brian/Desktop/Trading bot/python-binance-master/examples/RoibalBot.py", line 225, in visualize_market_depth
    ask_pri, ask_quan, bid_pri, bid_quan, ask_order, bid_order = market_depth(sym)
  File "/home/brian/Desktop/Trading bot/python-binance-master/examples/RoibalBot.py", line 146, in market_depth
    print("Order Book: ", convert_time_binance(client.get_server_time()))
  File "/home/brian/Desktop/Trading bot/python-binance-master/examples/RoibalBot.py", line 133, in convert_time_binance
    gg=int(aa)
ValueError: invalid literal for int() with base 10: "{u'serverTime': 1534530601778"

**Comment by brssnj54** [comment]
Okay, thanks Blockchain Engineer for the fix. 

Added this line of code to line 133 in the RoibalBot 

bb = aa.replace("{'serverTime': ","")
bb = aa.replace("{u'serverTime': ","")

Not sure why that worked...but now I'm running straight through without any errors...which is nice.

**Comment by Roibal** [comment]
this issue relates to roibal fork of python-binance and roibal underlying code, available here: https://github.com/Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance
