### ISSUE TITLE
method get_withdraw_fee returns an error

### ISSUE THREAD

**Issue by kolosovvs** [sammchardy/python-binance#325]
I am getting an error when I call this method  get_withdraw_fee(asset='ETH')

binance_client.get_withdraw_fee(asset='ETH')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Data/Dev/venv/lombard36/lib/python3.6/site-packages/binance/client.py", line 1760, in get_withdraw_fee
    return self._request_withdraw_api('get', 'withdrawFee.html', True, data=params)
  File "/Data/Dev/venv/lombard36/lib/python3.6/site-packages/binance/client.py", line 185, in _request_withdraw_api
    return self._request(method, uri, signed, True, **kwargs)
  File "/Data/Dev/venv/lombard36/lib/python3.6/site-packages/binance/client.py", line 175, in _request
    return self._handle_response(response)
  File "/Data/Dev/venv/lombard36/lib/python3.6/site-packages/binance/client.py", line 199, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=0): Invalid JSON error message from Binance: <html><head><title>Apache Tomcat/7.0.64 - Error report</title><style></style> </head><body><h1>HTTP Status 404 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.64</h3></body></html>

**Comment by ron7684** [comment]
The endpoint has been removed by Binance, use get_asset_details() instead.
