### ISSUE TITLE
Websocket errors after some time

### ISSUE THREAD

**Issue by MrNaif2018** [sammchardy/python-binance#366]
I am using user websocket, and after some time I always get that traceback. It seems to be not related to python binance itself, but it is a problem, maybe it is needed to switch to other websockets provider than autobahn. Or maybe it is needed to send websocket ping as I heard if not yet sending it.
Installed packages versions:
```
Name: python-binance
Version: 0.7.1
Name: requests
Version: 2.21.0
Name: six
Version: 1.12.0
Name: Twisted
Version: 18.9.0
Name: pyOpenSSL
Version: 19.0.0
Name: autobahn
Version: 19.1.1
Name: service-identity
Version: 18.1.0
Name: dateparser
Version: 0.7.0
Name: urllib3
Version: 1.24.1
Name: chardet
Version: 3.0.4
Name: cryptography
Version: 2.5
```
Traceback:
```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/usr/local/lib/python3.6/dist-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/local/lib/python3.6/dist-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/twisted/websocket.py", line 135, in dataReceived
    self._dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 1182, in _dataReceived
    self.consumeData()
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 1194, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 1560, in processData
    fr = self.onFrameEnd()
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 1682, in onFrameEnd
    self._onMessageEnd()
  File "/usr/local/lib/python3.6/dist-packages/autobahn/twisted/websocket.py", line 163, in _onMessageEnd
    self.onMessageEnd()
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 628, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/twisted/websocket.py", line 166, in _onMessage
    self.onMessage(payload, isBinary)
  File "/usr/local/lib/python3.6/dist-packages/binance/websockets.py", line 32, in onMessage
    self.factory.callback(payload_obj)
  File "api.py", line 180, in <lambda>
    conn_key = bm.start_user_socket(lambda msg:process_message(msg,i))
  File "api.py", line 120, in process_message
    order_id=process_one(msg,client,user_client,c)
  File "api.py", line 90, in process_one
    order_id=client2.order_market_sell(symbol=msg["s"],quantity=msg["q"])["orderId"]
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 1336, in order_market_sell
    return self.order_market(**params)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 1284, in order_market
    return self.create_order(**params)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 1149, in create_order
    return self._post('order', True, data=params)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 210, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 181, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 176, in _request
    return self._handle_response(response)
  File "/usr/local/lib/python3.6/dist-packages/binance/client.py", line 200, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/binance/websockets.py", line 514, in run
    reactor.run(installSignalHandlers=False)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 1267, in run
    self.mainLoop()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 1279, in mainLoop
    self.doIteration(t)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/tcp.py", line 519, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "/usr/local/lib/python3.6/dist-packages/twisted/protocols/tls.py", line 398, in connectionLost
    self._flushReceiveBIO()
  File "/usr/local/lib/python3.6/dist-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/local/lib/python3.6/dist-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/twisted/websocket.py", line 135, in dataReceived
    self._dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 1182, in _dataReceived
    self.consumeData()
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 1194, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 1552, in processData
    fr = self.onFrameData(payload)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 1647, in onFrameData
    self._onMessageFrameData(payload)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/twisted/websocket.py", line 154, in _onMessageFrameData
    self.onMessageFrameData(payload)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/websocket/protocol.py", line 602, in onMessageFrameData
    self.frame_data.append(payload)
builtins.AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by MrNaif2018** [comment]
Sorry, I didn't notice that it was caused by another error, but I expected another stack trace as on non market orders it never appears.

**Comment by sasa-buklijas** [comment]
I have similar problem.
Can you provide details what caused this error for your ?

I have 
```
"venv/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 601, in onMessageFrameData
    self.frame_data.append(payload)
builtins.AttributeError: 'NoneType' object has no attribute 'append'"
```
assuming do to:
```
pickle.dump(what_to_save, handle, protocol=pickle.HIGHEST_PROTOCOL)
builtins.RuntimeError: dictionary changed size during iterationd'"
```

But when I test changing of dict size while iterating, I do get 
"builtins.RuntimeError: dictionary changed size during iteration" 
but never
 "builtins.AttributeError: 'NoneType' object has no attribute 'append'".

Not expecting help, but maybe it will be useful to somebody, someday.

**Comment by MrNaif2018** [comment]
In my case exception in user websocket handler caused this, I simply missed the actual error. If error occurs in handler it will fail with such log. It was issue on my side

**Comment by sasa-buklijas** [comment]
> In my case exception in user websocket handler caused this, I simply missed the actual error. If error occurs in handler it will fail with such log. It was issue on my side

Thanks fro replay.

This is code that I wrote for testing

```
import time
from binance.websockets import BinanceSocketManager
from binance.client import Client

API_KEY = 'USER_YOUR_OWN'
API_SECRET = 'USER_YOUR_OWN'
client = Client(API_KEY, API_SECRET)

# call back
def process_message(msg):
    global c
    c +=  1
    print(f'Counter: {c}, id: {id(c)}')

    if (c % 2) == 0:
        global d

        for c1, (key, value) in enumerate(d.items()):
            print(c1, key, value)
    
            if c1 == 2:
                del d[key]
   
# MAIN
d = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6,}
c = 0

bm = BinanceSocketManager(client)
bm.daemon = True 
bm.name = 'WebSocket'
conn_key = bm.start_kline_socket('BTCUSDT', process_message,'1m')
if conn_key == False:
    print('---ERROR---')
    
# then start the socket manager
bm.start()
```
But it is only generating
"builtins.RuntimeError: dictionary changed size during iteration"
 never
"builtins.AttributeError: 'NoneType' object has no attribute 'append'".

**Comment by MrNaif2018** [comment]
Well, keep in mind that I got this error back in 2019, library mught have been updated since then. Probably now it shows correct error message.

**Comment by sasa-buklijas** [comment]
I have come to bottom of this, for future generations:

`"builtins.AttributeError: 'NoneType' object has no attribute 'append'".`

only appears, at leas in my experience, when you use `start_user_socket`, because it uses `autobahn` and then WebSocket is not automatically restarted. 
That is explaining why my test code with `start_kline_socket` did not reproduced error.
I could go in source code and investigate further, but for my use case it is not necessary.
