### ISSUE TITLE
Multiplex WebSockets error

### ISSUE THREAD

**Issue by georgeMuraveiAlkh** [sammchardy/python-binance#372]
Python 2.7.15 (pyenv)
OSX: Mojave 10.14.3
This error the same as https://github.com/sammchardy/python-binance/issues/318 I was getting this error on 0.7.0 version when created single socket connection. After update to 0.7.1 it was fixed for single connection but multiplex still giving same error.

```
from binance.client import Client
from binance.websockets import BinanceSocketManager
import params

client = Client(params.binance_public, params.binance_private)
bm = BinanceSocketManager(client)

def handle_socket(msg):
	print("message type: {}".format(msg['data']['e'])) 
	if msg['data']['e'] == 'error':
		# close and restart the socket
	else:
		# smth here
                 handle_htm_response(msg['data'])# An error occurs here!!!! It cant call this function because it is None
		
def handle_htm_response(data):
        # smth here
# conn_key = bm.start_kline_socket('BNBBTC', handleSocket) # WORKING
conn_key = bm.start_multiplex_socket(['bnbbtc@kline_1m', 'neobtc@kline_1m'], handle_socket) # NOT WORKING
bm.start()
```

```
Unhandled Error
Traceback (most recent call last):
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 135, in dataReceived
    self._dataReceived(data)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1182, in _dataReceived
    self.consumeData()
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1194, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1560, in processData
    fr = self.onFrameEnd()
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1682, in onFrameEnd
    self._onMessageEnd()
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 163, in _onMessageEnd
    self.onMessageEnd()
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 628, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 166, in _onMessage
    self.onMessage(payload, isBinary)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/binance/websockets.py", line 32, in onMessage
    self.factory.callback(payload_obj)
  File "/Users/georgezagraid/Projects/AI/Projects/Binance_Anomaly/main.py", line 21, in handle_socket
    handle_htm_response(msg['data'])
exceptions.TypeError: 'NoneType' object is not callable
```

So Sockets opened, callback function getting msg BUT it crashes when I even call another function or variable outside the callback function. So there is a trouble with right context.

**Comment by cryptobirr** [comment]
Hi How did you resolve this? I am having the same issue.
