### ISSUE TITLE
Error while multithreaded GET_HISTORICAL_KLINES

### ISSUE THREAD

**Issue by GeorgeMurAlkh** [sammchardy/python-binance#375]
I'm getting error while executing this code:
```
def handle_queue_get_klines(q, all_klines, stored_klines):
	while not q.empty():
		work = q.get()
		klines = client.get_historical_klines(work, Client.KLINE_INTERVAL_1MINUTE, '15 days ago UTC')
		all_klines[work] = klines
		stored_klines[work] = utils.fromKlinesToOHLC(klines[-params.klines_store_length:])
		q.task_done()

for symbol in symbols:
	#put workers in queue.
	q_klines.put((symbol))

for i in range(num_theads_klines):
	 worker = Thread(target=handle_queue_get_klines, args=[q_klines, all_klines, stored_klines])
	 worker.setDaemon(True)
	 worker.start()
	
q_klines.join()
```

```
Traceback (most recent call last):
  File "/Users/georgezagraid/.vscode/extensions/ms-python.python-2019.2.5558/pythonFiles/ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "/Users/georgezagraid/.vscode/extensions/ms-python.python-2019.2.5558/pythonFiles/lib/python/ptvsd/__main__.py", line 357, in main
    run()
  File "/Users/georgezagraid/.vscode/extensions/ms-python.python-2019.2.5558/pythonFiles/lib/python/ptvsd/__main__.py", line 257, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/georgezagraid/Projects/AI/Projects/Binance_Anomaly/main.py", line 171, in <module>
    start_detection()
  File "/Users/georgezagraid/Projects/AI/Projects/Binance_Anomaly/main.py", line 122, in start_detection
    klines = client.get_historical_klines(symbol, Client.KLINE_INTERVAL_1MINUTE, '{0} ago UTC'.format(params.klines_interval_str))
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/binance/client.py", line 762, in get_historical_klines
    start_ts = date_to_milliseconds(start_str)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/binance/helpers.py", line 22, in date_to_milliseconds
    d = dateparser.parse(date_str)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/dateparser/conf.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/dateparser/__init__.py", line 53, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/dateparser/date.py", line 404, in get_date_data
    locale, date_string, date_formats, settings=self._settings)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/dateparser/date.py", line 177, in parse
    return instance._parse()
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/dateparser/date.py", line 187, in _parse
    date_obj = parser()
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/dateparser/date.py", line 200, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/dateparser/freshness_date_parser.py", line 148, in get_date_data
    date, period = self.parse(date_string, settings)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/dateparser/freshness_date_parser.py", line 97, in parse
    date, period = self._parse_date(date_string)
  File "/Users/georgezagraid/.pyenv/versions/2.7.15/envs/htm-env/lib/python2.7/site-packages/dateparser/freshness_date_parser.py", line 133, in _parse_date
    date = self.now - td
TypeError: unsupported operand type(s) for -: 'NoneType' and 'relativedelta'
```

So if I changing '15 days ago UTC' to 1552554171 to not force dateparser to execute - threads started but seems to never end getting klines. How can I get more klines at the same time?

**Comment by VMobileRecords** [comment]
I'm also interested in this as I get the same type of error when trying to get multiple historical klines at the same time by using QRunnable and QThreadPool.

In my application I have 6 intervals for which I want to get the klines, so I'm trying to run each interval on a separate Thread.

Thanks in advance for the help.

**Comment by georgeMuraveiAlkh** [comment]
> I'm also interested in this as I get the same type of error when trying to get multiple historical klines at the same time by using QRunnable and QThreadPool.
> 
> In my application I have 6 intervals for which I want to get the klines, so I'm trying to run each interval on a separate Thread.
> 
> Thanks in advance for the help.

I found that when I'm using 
```
from threading import Timer
Timer(seconds, restart_detection).start()

```
Inside ```restart_detection``` I'm getting klines while websockets opened and It's kinda working (but I'm using Timer for different purpose)
