### ISSUE TITLE
Issues with feature/asyncio branch: userstream keep alive/ maintain connection

### ISSUE THREAD

**Issue by bas20150622** [sammchardy/python-binance#400]
Hello, thanks for a great program!
Recently I tried the websocket functionality using the main branch but had issues in keeping the userstream alive that I thought were the result of twisted. However after trying the asyncio branch I unfortunately get the same result. After a period of time (< 24hrs) the stream is no longer alive - no error messages. Is there any way to find out what causes it (logging?)?

**Comment by bas20150622** [comment]
> Hello, thanks for a great program!
> Recently I tried the websocket functionality using the main branch but had issues in keeping the userstream alive that I thought were the result of twisted. However after trying the asyncio branch I unfortunately get the same result. After a period of time (< 24hrs) the stream is no longer alive - no error messages. Is there any way to find out what causes it (logging?)?

Enabling asyncio debugging gave following (essential) logging output:
Traceback (most recent call last):
  File "binance_logger.py", line 57, in <module>
    loop.run_until_complete(main())
  File "/home//lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "binance_logger.py", line 44, in main
    usr_conn_key = await bm.start_user_socket(handle_message)
  File "/home//binance/websockets.py", line 459, in start_user_socket
    conn_key = await self._start_user_socket(user_listen_key, coro)
  File "/home//binance/websockets.py", line 475, in _start_user_socket
    self._start_user_timer()
  File "/home//binance/websockets.py", line 480, in _start_user_timer
    self._user_timer = self._loop.call_later(self._user_timeout, self._keepalive_user_socket)
  File "/home//lib/python3.7/asyncio/base_events.py", line 646, in call_later
    context=context)
  File "/home//lib/python3.7/asyncio/base_events.py", line 659, in call_at
    self._check_callback(callback, 'call_at')
  File "/home//lib/python3.7/asyncio/base_events.py", line 690, in _check_callback
    f"coroutines cannot be used with {method}()")
TypeError: coroutines cannot be used with call_at()
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fbdaea00080>
source_traceback: Object created at (most recent call last):
  File "binance_logger.py", line 57, in <module>
    loop.run_until_complete(main())
  File "/home//lib/python3.7/asyncio/base_events.py", line 560, in run_until_complete
    self.run_forever()
  File "/home//lib/python3.7/asyncio/base_events.py", line 528, in run_forever
    self._run_once()
  File "/home//lib/python3.7/asyncio/base_events.py", line 1756, in _run_once
    handle._run()
  File "/home//lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "binance_logger.py", line 29, in main
    client = await AsyncClient.create(SECRET['apiKey'], SECRET['secret'])
  File "/home//binance/client.py", line 2090, in create
    self = AsyncClient(api_key, api_secret, requests_params)
  File "/home//binance/client.py", line 94, in __init__
    self.session = self._init_session()
  File "/home//binance/client.py", line 2101, in _init_session
    headers=self._get_headers()
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fbdae5da948>, 866040.210375473)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fbdaea000b8>
source_traceback: Object created at (most recent call last):
  File "binance_logger.py", line 57, in <module>
    loop.run_until_complete(main())
  File "/home//lib/python3.7/asyncio/base_events.py", line 560, in run_until_complete
    self.run_forever()
  File "/home//lib/python3.7/asyncio/base_events.py", line 528, in run_forever
    self._run_once()
  File "/home//lib/python3.7/asyncio/base_events.py", line 1756, in _run_once
    handle._run()
  File "/home//lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "binance_logger.py", line 29, in main
    client = await AsyncClient.create(SECRET['apiKey'], SECRET['secret'])
  File "/home//binance/client.py", line 2090, in create
    self = AsyncClient(api_key, api_secret, requests_params)
  File "/home//binance/client.py", line 94, in __init__
    self.session = self._init_session()
  File "/home//binance/client.py", line 2101, in _init_session
    headers=self._get_headers()
  File "/home//lib/python3.7/site-packages/aiohttp/client.py", line 204, in __init__
    connector = TCPConnector(loop=loop)
  File "/home//lib/python3.7/site-packages/aiohttp/connector.py", line 730, in __init__
    loop=loop)

**Comment by alexcrownjr** [comment]
I have something similar, but after few hours

src/client.py:324: RuntimeWarning: coroutine '_keepalive_user_socket' was never awaited
loop.run_until_complete(main_task(loop, connections))

and then after 10-20 minutes my client restarts

sow this few times

**Comment by miraclix** [comment]
Any solution found?

**Comment by miraclix** [comment]
I am having more luck with unicorn binance websocket module.

**Comment by sammchardy** [comment]
@bas20150622 @alexcrownjr  @miraclix  I have pushed an update to the feature/asyncio branch to improve the reconnecting of the websocket and also fixing the `_keepalive_user_socket` error.

**Comment by bas20150622** [comment]
Testing it now, will let you know  > 24hrs testing

**Comment by bas20150622** [comment]
Works like a charm now, thanks Sam!
