### ISSUE TITLE
Illegal characters found in parameter 'endTime'; legal range is '^[0-9]{1,20}$'

### ISSUE THREAD

**Issue by MathieuCesbron** [sammchardy/python-binance#417]
**CODE:**

from binance.client import Client

apiKey = "" #Removed in GitHub for obvious reason
secretKey = "" #Removed in GitHub for obvious reason

client = Client(apiKey, secretKey)

klines = client.get_historical_klines(
    "BNBBTC", Client.KLINE_INTERVAL_1MINUTE, "1 day ago UTC"
)

print(klines)

**OUTPUT:** 

Traceback (most recent call last):
  File "c:\Users\mathieu\Desktop\Bot\Backtrade\test.py", line 13, in <module>
    "BNBBTC", Client.KLINE_INTERVAL_1MINUTE, "1 day ago UTC"
  File "C:\Users\mathieu\.virtualenvs\mathieu-Ku3GWNc4\lib\site-packages\binance\client.py", line 775, in get_historical_klines
    first_valid_ts = self._get_earliest_valid_timestamp(symbol, interval)
  File "C:\Users\mathieu\.virtualenvs\mathieu-Ku3GWNc4\lib\site-packages\binance\client.py", line 733, in _get_earliest_valid_timestamp
    endTime=None
  File "C:\Users\mathieu\.virtualenvs\mathieu-Ku3GWNc4\lib\site-packages\binance\client.py", line 715, in get_klines
    return self._get('klines', data=params)
  File "C:\Users\mathieu\.virtualenvs\mathieu-Ku3GWNc4\lib\site-packages\binance\client.py", line 217, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\mathieu\.virtualenvs\mathieu-Ku3GWNc4\lib\site-packages\binance\client.py", line 186, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\mathieu\.virtualenvs\mathieu-Ku3GWNc4\lib\site-packages\binance\client.py", line 181, in _request
    return self._handle_response(response)
  File "C:\Users\mathieu\.virtualenvs\mathieu-Ku3GWNc4\lib\site-packages\binance\client.py", line 210, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'endTime'; legal range is '^[0-9]{1,20}$'.

**Expected behavior**
I succesfully installed python-binance, everything works ( I can have market depth, ...) excecpt for Client.KLINE_INTERVAL_1MINUTE who give me an error.

**Environment:**
 - Python version: 3.7
 - Virtual Env: virtualenv
 - OS: Windows
 - python-binance version v0.7.3

**Logs or Additional context**
I already managed it to run but it was on another computer and it was 3 months ago, I don't see my mistake here.

**Comment by muhlar** [comment]
I have the same issue. Downgraded to 0.7.2 as temp fix.

**Comment by workofart** [comment]
Yeah, I got the same error this morning. The reason I believe is because python-binance is sending endTime as None in Client.get_klines(), so binance thinks endTime parameter exists on the request and validates the None values against its regex. I believe this pull request addresses this, it strips the None from the parameters so that it doesn't trigger validation from binance's api server.

**Comment by ABUJOUDAH** [comment]
are you found the solution ??

**Comment by AlfaTelecom** [comment]
I find the solution by passing the starTime and the endTime as integers, in miliseconds.
