### ISSUE TITLE
V0.74    APIError(code=-1022): Signature for this request is not valid.

### ISSUE THREAD

**Issue by wanyanozaccess** [sammchardy/python-binance#436]
**Describe the bug**
V0.74    
APIError(code=-1022): Signature for this request is not valid.

**To Reproduce**
client.get_margin_loan_details(asset='BTC', txId=nnnnnnnnnn)

**Expected behavior**
Loan detail returned

**Environment (please complete the following information):**
 - Python version: 2.7
 - Virtual Env: none
 - OS: Debian
 - python-binance version 0.74

**Logs or Additional context**
Traceback (most recent call last):
  File "BTCUSDT-Short.py", line 37, in <module>
    client.get_margin_loan_details(asset='BTC', txId=nnnnnnnn)
  File "~/python-binance/binance/client.py", line 2628, in get_margin_loan_details
    return self._request_margin_api('get', 'margin/loan', signed=True, data=params)
  File "~/python-binance/binance/client.py", line 201, in _request_margin_api
    return self._request(method, uri, signed, **kwargs)
  File "~/python-binance/binance/client.py", line 186, in _request
    return self._handle_response()
  File "~/python-binance/binance/client.py", line 215, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1022): Signature for this request is not valid.
Press any key to continue...

**Comment by wanyanozaccess** [comment]
My fault, please ignore this.
