### ISSUE TITLE
order_market_buy: binance.exceptions.BinanceAPIException: APIError(code=-1104): Not all sent parameters were read; read '5' parameter(s) but was sent '6'.

### ISSUE THREAD

**Issue by chaudoe** [sammchardy/python-binance#472]
Hi, I'm trying to place order by market price for XRPUSDT pair:

```
buy_order = client.order_market_buy(symbol='XRPUSDT', quanityt=100)

sell_order = client.order_market_sell(symbol='XRPUSDT', quanityt=100)
```
but it keeps firing errors from client.py module

```
Traceback (most recent call last):
  line 29, in <module>
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 1325, in order_market_buy
    return self.order_market(**params)
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 1299, in order_market
    return self.create_order(**params)
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 1164, in create_order
    return self._post('order', True, data=params)
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 225, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 191, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 186, in _request
    return self._handle_response()
  File "C:\Users\chaum\AppData\Local\Programs\Python\Python38\lib\site-packages\binance\client.py", line 215, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1104): Not all sent parameters were read; read '5' parameter(s) but was sent '6'.
```
not sure why but aren't only 2 parameters required?

**Comment by NeoBreedZ** [comment]
Hello, I am writing a bot now, I encountered the same error, here is a request to buy and sell, if it is still relevant, I am happy to help)))


`from binance.client import Client
from binance.enums import * # Import this, otherwise order placement won't work


api_key = 'XsZAaUwuwf1KWRhdolC20TbdjcwgSwLlCSLHNMHrUd7zmd8rD5D2taTAq7uG2l7b'
api_secret = 'XR5HNq2poJ8Cq5bEhH3uhNaGvnKD3TyHbFJ92Nvg4G1tNRxoGKIfZqFbTWHqmyEf'
client = Client(api_key, api_secret)

order = client.create_order(
	symbol='XRPUSDT', # Currency pair
	side=SIDE_SELL, # Buy USDT for XRP (29 pcs), if you want to buy XRP for USDT, write SIDE_BUY instead of SIDE_SELL
	type=ORDER_TYPE_MARKET, # Sell at market price
	quantity=29) # XRP amount`


Rewrite the code carefully, or copy it better, otherwise I misspelled the word 'quantity' and I got your error)

**Comment by fabianmendes** [comment]
Hi, excuse me@NeoBreedZ  you should delete your bot api strings values from here, dude

**Comment by animax1991** [comment]
Is there any fixes for order_market_buy function? Or we have to use @NeoBreedZ as temporary solution?
