### ISSUE TITLE
requests.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by andyquek** [sammchardy/python-binance#540]
C:\Users\andyq\PycharmProjects\BinanceTrading\venv\Scripts\python.exe C:/Users/andyq/PycharmProjects/BinanceTrading/thisbetterwork(trail).py
Traceback (most recent call last):
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\andyq\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\andyq\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\andyq\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\andyq\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\urllib3\contrib\pyopenssl.py", line 326, in recv_into
    raise timeout("The read operation timed out")
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\urllib3\connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\urllib3\connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/andyq/PycharmProjects/BinanceTrading/thisbetterwork(trail).py", line 1186, in <module>
    btc_price = client.get_margin_price_index(symbol='BTCUSDT')
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\binance\client.py", line 2498, in get_margin_price_index
    return self._request_margin_api('get', 'margin/priceIndex', data=params)
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\binance\client.py", line 212, in _request_margin_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\binance\client.py", line 196, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\andyq\PycharmProjects\BinanceTrading\venv\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

Process finished with exit code 1

**Comment by egrgad** [comment]
Same problem, I can't solve it myself

**Comment by EUA** [comment]
I got this too. Can't find how to avoid that, yet.
