### ISSUE TITLE
start_multiplex_socket Unhandled Error

### ISSUE THREAD

**Issue by teterevlev** [sammchardy/python-binance#634]
**Describe the bug**
Using start_multiplex_socket causes Unhandled Error:
```>>> Unhandled Error
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\protocols\tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\twisted\websocket.py", line 290, in dataReceived
    self._dataReceived(data)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 1207, in _dataReceived
    self.consumeData()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 1219, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 1579, in processData
    fr = self.onFrameEnd()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 1704, in onFrameEnd
    self._onMessageEnd()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\twisted\websocket.py", line 318, in _onMessageEnd
    self.onMessageEnd()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 628, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\twisted\websocket.py", line 321, in _onMessage
    self.onMessage(payload, isBinary)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\websockets.py", line 32, in onMessage
    self.factory.callback(payload_obj)
  File "<stdin>", line 2, in process_message

builtins.KeyError: 'e'

Unhandled Error
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\binance\websockets.py", line 586, in run
    reactor.run(installSignalHandlers=False)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\base.py", line 1283, in run
    self.mainLoop()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\base.py", line 1295, in mainLoop
    self.doIteration(t)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\selectreactor.py", line 143, in doSelect
    _logrun(selectable, _drdw, selectable, method)
--- <exception caught here> ---
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\selectreactor.py", line 154, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, method=="doRead")
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\tcp.py", line 519, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\internet\tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\protocols\tls.py", line 398, in connectionLost
    self._flushReceiveBIO()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\protocols\tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\twisted\protocols\policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\twisted\websocket.py", line 290, in dataReceived
    self._dataReceived(data)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 1207, in _dataReceived
    self.consumeData()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 1219, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 1571, in processData
    fr = self.onFrameData(payload)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 1666, in onFrameData
    self._onMessageFrameData(payload)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\twisted\websocket.py", line 309, in _onMessageFrameData
    self.onMessageFrameData(payload)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\autobahn\websocket\protocol.py", line 602, in onMessageFrameData
    self.frame_data.append(payload)
builtins.AttributeError: 'NoneType' object has no attribute 'append'
```
**To Reproduce**
Code snippet to reproduce the behavior:
```from binance.client import Client
from binance.websockets import BinanceSocketManager
client = Client('***', '***')
def process_message(msg):
    print("message type: {}".format(msg['e']))
    print(msg)

bm = BinanceSocketManager(client)
conn_key = bm.start_multiplex_socket(['bnbbtc@trade'], process_message)
```
**Expected behavior**
Using
```
conn_key = bm.start_trade_socket('BNBBTC', process_message)
```
instead of
```
conn_key = bm.start_multiplex_socket(['bnbbtc@trade'], process_message)
```
works fine:
```message type: trade
{'e': 'trade', 'E': 1608972205205, 's': 'BNBBTC', 't': 97456620, 'p': '0.00133380', 'q': '0.11000000', 'b': 630911643, 'a': 630911505, 'T': 1608972205204, 'm': False, 'M': True}
```
**Environment:**
 - Python version: 3.7 (64-bit)
 - Virtual Env: command line
 - OS: Windows 10
 - python-binance version: 0.7.5

On Ubuntu Server behavoir is the same:
 - Python version: Python 3.6.9
 - Virtual Env: command line
 - OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0 x86_64)
 - python-binance version: 0.7.0

**Comment by oliver-zehentleitner** [comment]
I think you are trying to use the array key 'e' but it doesnt exist! 

remove the part
```
 print("message type: {}".format(msg['e']))
```
of your code and run it again.

**Comment by teterevlev** [comment]
Thank you! Sorry for my carelessness
