### ISSUE TITLE
Trying to buy - Mandatory parameter 'symbol' was not sent, was empty/null, or malformed.

### ISSUE THREAD

**Issue by deaton1337** [sammchardy/python-binance#718]
Hello,

I'm trying to do a simple buy order, but I'm getting an error stating the symbol was not sent. I've made this as simple as I can, but I'm still getting the error.
I've got Bitcoin in my Binance wallet and my API key is allowed to do Spot & Margin Trading. I can read everything fine, but as soon as I try a buy, I get the error.
I'm running Python 3.8 on Windows WSL2, with Ubuntu 20.04.

Thanks for any advice.

David

Here's my code:
`print(binance_client.get_symbol_ticker(symbol='CRVBTC'))`
`order = binance_client.order_market_buy(symbol='CRVBTC',quantity=6)`

Here's the output/error I get:

```
{'symbol': 'CRVBTC', 'price': '0.00004500'}
Traceback (most recent call last):
  File "./buy.py", line 220, in <module>
    main()
  File "./buy.py", line 215, in main
    buy_coin(stake)
  File "./buy.py", line 172, in buy_coin
    order = binance_client.order_market_buy(symbol='CRVBTC',quantity=6)
  File "/home/david/env3/lib/python3.8/site-packages/binance/client.py", line 1366, in order_market_buy
    return self.order_market(**params)
  File "/home/david/env3/lib/python3.8/site-packages/binance/client.py", line 1338, in order_market
    return self.create_order(**params)
  File "/home/david/env3/lib/python3.8/site-packages/binance/client.py", line 1200, in create_order
    return self._post('order', True, data=params)
  File "/home/david/env3/lib/python3.8/site-packages/binance/client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/david/env3/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/david/env3/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/david/env3/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1102): Mandatory parameter 'symbol' was not sent, was empty/null, or malformed.
```

**Comment by deaton1337** [comment]
My fault. I was setting the API url to https://binance.com/api
I removed that and it worked.
