### ISSUE TITLE
Failed to parse error [SOLVED]

### ISSUE THREAD

**Issue by fuzzybannana** [sammchardy/python-binance#773]
My code works fine If I'm running it using VScode with the Python virtualenv
Python version: [3.8.5] 64-bit

however if I run the same code in the terminal using Python [3.8.5] 64-bit
I get this error here

nick-pc@nickpc-HP-xw4300-Workstation:~/Documents/pythonprojects/DCAbot$ /usr/bin/python3 /home/nick-pc/Documents/pythonprojects/DCAbot/DCAETHbot.py 

Traceback (most recent call last):
  File "/home/nick-pc/.local/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://api.binance.com/api/v3/ping

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nick-pc/Documents/pythonprojects/DCAbot/DCAETHbot.py", line 8, in <module>
    client = Client(keys.api_key, keys.api_secret) 
  File "/home/nick-pc/.local/lib/python3.8/site-packages/binance/client.py", line 105, in __init__
    self.ping()
  File "/home/nick-pc/.local/lib/python3.8/site-packages/binance/client.py", line 392, in ping
    return self._get('ping', version=self.PRIVATE_API_VERSION)
  File "/home/nick-pc/.local/lib/python3.8/site-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home/nick-pc/.local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/nick-pc/.local/lib/python3.8/site-packages/binance/client.py", line 196, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/home/nick-pc/.local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/nick-pc/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/nick-pc/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/nick-pc/.local/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/nick-pc/.local/lib/python3.8/site-packages/requests/models.py", line 384, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://api.binance.com/api/v3/ping 

 - Python version: [3.8.5] 64-bit
 - Virtual Env: [virtualenv]
 - OS: [Ubuntu]
 - python-binance version [0.7.9]

**Comment by fuzzybannana** [comment]
uh nevermind I think I solved this issue by updating urllib3
python -m pip install --upgrade urllib3
