### ISSUE TITLE
APIError(code=-2015): Invalid API-key, IP, or permissions for action. When getting account info

### ISSUE THREAD

**Issue by numerocat** [sammchardy/python-binance#778]
When i run the python script 
balance = client.get_asset_balance(asset="USDT")
i get the error -2015

I have 2 api´s, i dont know if that has a role there, i already checked that those are the correct keys.
The permissions enabled are:
reading
spot and margin trading
withdrawals
universal transfer
vanilla options

Reproduce the error:
from binance.client import Client
client = Client("mykey", "mykey", tld='us')
balance = client.get_asset_balance(asset="USDT")

Full error lines:
Traceback (most recent call last):
  File "lol.py", line 19, in <module>
    balance = client.get_asset_balance(asset="USDT")
  File "C:\Users\numerocat\.conda\envs\bot\lib\site-packages\binance\client.py", line 1847, in get_asset_balance
    res = self.get_account(**params)
  File "C:\Users\numerocat\.conda\envs\bot\lib\site-packages\binance\client.py", line 1822, in get_account
    return self._get('account', True, data=params)
  File "C:\Users\numerocat\.conda\envs\bot\lib\site-packages\binance\client.py", line 292, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\numerocat\.conda\envs\bot\lib\site-packages\binance\client.py", line 242, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\numerocat\.conda\envs\bot\lib\site-packages\binance\client.py", line 237, in _request
    return self._handle_response()
  File "C:\Users\numerocat\.conda\envs\bot\lib\site-packages\binance\client.py", line 285, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2015): Invalid API-key, IP, or permissions for action.

**Comment by egcodes** [comment]
for test try this

```python
client = Client(api_key, api_secret)
client.API_URL = "https://testnet.binance.vision/api"
```

but there must be a better way to convert all api to test
![image](https://user-images.githubusercontent.com/3457067/115447975-cb198580-a221-11eb-8e42-4ee6a202ed65.png)

**Comment by numerocat** [comment]
> for test try this
> 
> ```python
> client = Client(api_key, api_secret)
> client.API_URL = "https://testnet.binance.vision/api"
> ```
> 
> but there must be a better way to convert all api to test
> ![image](https://user-images.githubusercontent.com/3457067/115447975-cb198580-a221-11eb-8e42-4ee6a202ed65.png)

Thanks, looks like removing the third argument in Client object fixed it.
Awesome!

**Comment by emrahkirdok** [comment]
Hi, I have also the same error. All the api keys new and relevant permissions are granted. BTW, I am using https://www.trbinance.com

Do you know how can I fix it? Thank you for the help.
e

**Comment by numerocat** [comment]
You should search for the "tld=" argument as i said in my last reply, check it and change it if necessary. I am sorry that i cant help you any further, good luck.

**Comment by alexrmacleod** [comment]
here is the answer, gotta create a testnet api key which is different to the regular api key via the binance testnet docs 

https://stackoverflow.com/questions/67376632/how-to-create-binance-test-api-key

https://testnet.binance.vision/ (click generate api)
