### ISSUE TITLE
get_historical_klines_generator - APIError(code=-1104)

### ISSUE THREAD

**Issue by SteveChurch** [sammchardy/python-binance#799]
**Describe the bug**
Using `get_historical_klines_generator` Causes APIError 1104

**To Reproduce**
```
            for klines in client.get_historical_klines_generator(
                    symbol="BTCUSDT",
                    interval=Client.KLINE_INTERVAL_1MINUTE,
                    start_str="1 Jan, 2005 UTC"
            ):
                store_candles(klines, pair)
```
**Expected behavior**

**Environment (please complete the following information):**
 - Python version: 3.8
 - Virtual Env: Docker
 - OS: OSX
 - python-binance version 0.7.11

**Logs or Additional context**
```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/code/apps/crypto/management/commands/store_history_alltime.py", line 56, in handle
    for klines in client.get_historical_klines_generator(
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 1032, in _historical_klines_generator
    output_data = self.get_klines(
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 817, in get_klines
    return self._get('klines', data=params, version=self.PRIVATE_API_VERSION)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 320, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 265, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 260, in _request
    return self._handle_response()
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 313, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1104): Not all sent parameters were read; read '4' parameter(s) but was sent '5'.
```

**Comment by SteveChurch** [comment]
Interesting, We're passing `spot` to the API.

IT doesn't accept spot..

<img width="517" alt="image" src="https://user-images.githubusercontent.com/458008/116758211-7dfa9800-aa07-11eb-9960-411417eb30aa.png">

**Comment by SteveChurch** [comment]
```
output_data = self.get_klines(
                spot=spot,
                symbol=symbol,
                interval=interval,
                limit=limit,
                startTime=start_ts,
                endTime=end_ts
            )
```

Problem Above. Ill raise a PR.. `spot` is making it's way through to the API

**Comment by SteveChurch** [comment]
https://github.com/sammchardy/python-binance/blob/ea11f4c212c43223e2cd212e3d53c435c940c704/binance/client.py#L1032

Issue above. Spot is not being handled properly and instead being passed through to the API

**Comment by sammchardy** [comment]
This should now be fixed in v1.0.0

**Comment by SteveChurch** [comment]
Thanks @sammchardy
