### ISSUE TITLE
how to Ping/Keep-alive a ListenKey (USER_STREAM)

### ISSUE THREAD

**Issue by PiyushDixit96** [sammchardy/python-binance#825]
**Ping/Keep-alive a ListenKey (USER_STREAM)**

**my code**

```sh
async def spot_user(client):
    bm = BinanceSocketManager(client)
    logger.info("Binance futures Socket Manager started..")
    async with bm.futures_socket() as stream:
        while True:
            print(True)
            res = await stream.recv()
            if res is not None:
                logger.info(f"futures Socket Message Received: {res['e']}")

                print(json.dumps(res,indent=2))
            else:
                logger.error(f"futures Socket Message Received: {res}")
            
async def main():
    client = await AsyncClient.create(api_key=api_key,api_secret=api_secret)
    await spot_user(client)

if __name__ == "__main__":

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

error " listenKeyExpired "

**In binance api docs** 
Keepalive a user data stream to prevent a time out. User data streams will close after 60 minutes. It's recommended to send a ping about every 30 minutes.

how to send a ping about every 30 minutes?
please share full code(include my code too) for this.
please help me for this.

**Comment by sammchardy** [comment]
Your code is fine.
Have resolved an issue in v1.0.6. with the keepalives not being sent for the authenticated streams

**Comment by PiyushDixit96** [comment]
i test it and "listenKeyExpired" goen but while testing this error thrown

```sh
listen key same: keepalive
listen key same: keepalive
05/09/2021 06:14:58 PM India Standard Time - __main__ - INFO - futures Socket Message Received: ACCOUNT_UPDATE
{
  "e": "ACCOUNT_UPDATE",
  "T": 1620564298803,
  "E": 1620564298808,
  "a": {
    "B": [
      {
        "a": "USDT",
        "wb": "0.04258721",
        "cw": "0.04258721",
        "bc": "0.04258721"
      }
    ],
    "P": [],
    "m": "DEPOSIT"
  }
}
listen key same: keepalive
listen key same: keepalive
listen key same: keepalive
05/09/2021 06:15:21 PM India Standard Time - __main__ - INFO - futures Socket Message Received: ACCOUNT_UPDATE
{
  "e": "ACCOUNT_UPDATE",
  "T": 1620564321779,
  "E": 1620564321783,
  "a": {
    "B": [
      {
        "a": "USDT",
        "wb": "0",
        "cw": "0",
        "bc": "-0.04258721"
      }
    ],
    "P": [],
    "m": "WITHDRAW"
  }
}
listen key same: keepalive
listen key same: keepalive
listen key same: keepalive
05/09/2021 06:15:40 PM India Standard Time - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2084' coro=<KeepAliveWebsocket._keepalive_socket() done, defined at C:\Users\******\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\streams.py:216> exception=BinanceAPIException(<ClientResponse(https://fapi.binance.com/fapi/v1/listenKey?listenKey=V0ZlgbP********************************Hj9d5TiyAJypBmWVBY8g) [502 Bad Gateway]>
<CIMultiDictProxy('Content-Type': 'text/html', 'Content-Length': '1033', 'Connection': 'keep-alive', 'Server': 'CloudFront', 'Date': 'Sun, 09 May 2021 12:45:41 GMT', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 1c8c957c4a5bf12***********0ec6570.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'BOM50-C1', 'X-Amz-Cf-Id': 'W1Bz6uYbDwVd9***********TvP7_Fm7STWg1g-3ZIuSESeA==')>
, 502, '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>502 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size="1px">\nCloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.\nWe can\'t connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear="all">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n<BR clear="all">\n<HR noshade size="1px">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: E_c3s1IcddQEb6Z*********************m3h07xkbA==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>')>
Traceback (most recent call last):
  File "C:\Users\*******\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\streams.py", line 230, in _keepalive_socket
    await self._client.futures_stream_keepalive(self._path)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 7362, in futures_stream_keepalive
    return await self._request_futures_api('put', 'listenKey', signed=False, data=params)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 6471, in _request_futures_api
    return await self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\*******\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 6449, in _request
    return await self._handle_response(response)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 6457, in _handle_response
    raise BinanceAPIException(response, response.status, await response.text())
binance.exceptions.BinanceAPIException: APIError(code=0): Invalid JSON error message from Binance: <bound method ClientResponse.text of <ClientResponse(https://fapi.binance.com/fapi/v1/listenKey?listenKey=V0ZlgbPufLPMccMF***********************************AJypBmWVBY8g) [502 Bad Gateway]>
<CIMultiDictProxy('Content-Type': 'text/html', 'Content-Length': '1033', 'Connection': 'keep-alive', 'Server': 'CloudFront', 'Date': 'Sun, 09 May 2021 12:45:41 GMT', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 1c8c95********************************570.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'BOM50-C1', 'X-Amz-Cf-Id': 'W1Bz6uYbDw*********************************Fm7STWg1g-3ZIuSESeA==')>
>
05/09/2021 06:16:24 PM India Standard Time - __main__ - ERROR - futures Socket Message Received: None
listen key same: keepalive
listen key same: keepalive
listen key same: keepalive
```

**Comment by PiyushDixit96** [comment]
i don't know above error is related to your repo or not.
if not related to your repo then close this issue.
Thanks
