### ISSUE TITLE
the reconnection does not seem to work 

### ISSUE THREAD

**Issue by motumboe** [sammchardy/python-binance#834]
If I run the following program:
```
import asyncio
from binance import AsyncClient, BinanceSocketManager
import logging 

async def kline_listener(client):
	bm = BinanceSocketManager(client)
	async with bm.kline_socket(symbol='BNBBTC') as stream:
		while True:
			res = await stream.recv()
			print(res)

async def main():
	client = await AsyncClient.create()
	await kline_listener(client)

if __name__ == "__main__":
	logging.basicConfig(filename='example.log', filemode='w', level=logging.DEBUG)
	loop = asyncio.get_event_loop()
	loop.run_until_complete(main())
```
...and I disconnect the ethernet cable after a few messages, after about a minute I get:
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-28563' coro=<ReconnectingWebsocket._reconnect() done, defined at /home/xxxx/pb/env/lib/python3.8/site-packages/binance/streams.py:152> exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/home/xxxx/pb/env/lib/python3.8/site-packages/binance/streams.py", line 166, in _reconnect
    await self.connect()
  File "/home/xxxx/pb/env/lib/python3.8/site-packages/binance/streams.py", line 70, in connect
    self.ws = await self._conn.__aenter__()
  File "/home/xxxx/pb/env/lib/python3.8/site-packages/websockets/legacy/client.py", line 604, in __aenter__
    return await self
  File "/home/xxxx/pb/env/lib/python3.8/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 986, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1365, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```
Full debug log is here: [debug-log.txt](https://github.com/sammchardy/python-binance/files/6445230/example.log)
The issue is reproducible.

**Comment by sammchardy** [comment]
Have pushed a change that should catch these errors when there's no network connection on connect/reconnect.

I will update the version in the next day or so with this change as well.

**Comment by motumboe** [comment]
Hi Sam!
  The change did not fix the issue, see the log from the same program when I disconnect:
```
(...)
DEBUG:websockets.protocol:client - event = data_received(<182 bytes>)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{"e":"kline","E":1621399903598,"s":"BNBBTC","k":{"t":1621399860000,"T":1621399919999,"s":"BNBBTC","i":"1m","f":144143234,"L":144143776,"o":"0.01074300","c":"0.01067600","h":"0.01074400","l":"0.01065900","v":"990.68000000","n":543,"x":false,"q":"10.59152789","V":"330.24000000","Q":"3.53024252","B":"0"}}', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client - event = data_received(<183 bytes>)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{"e":"kline","E":1621399905847,"s":"BNBBTC","k":{"t":1621399860000,"T":1621399919999,"s":"BNBBTC","i":"1m","f":144143234,"L":144143788,"o":"0.01074300","c":"0.01066900","h":"0.01074400","l":"0.01065900","v":"1000.94000000","n":555,"x":false,"q":"10.70104256","V":"338.67000000","Q":"3.62022413","B":"0"}}', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client - event = data_received(<182 bytes>)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{"e":"kline","E":1621399907866,"s":"BNBBTC","k":{"t":1621399860000,"T":1621399919999,"s":"BNBBTC","i":"1m","f":144143234,"L":144143838,"o":"0.01074300","c":"0.01066300","h":"0.01074400","l":"0.01065700","v":"1013.15000000","n":605,"x":false,"q":"10.83124639","V":"343.38000000","Q":"3.67046311","B":"0"}}', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=<Opcode.PING: 9>, data=b'3{QT', rsv1=False, rsv2=False, rsv3=False)
DEBUG:root:no message in 10 seconds
DEBUG:root:no message in 10 seconds
DEBUG:websockets.protocol:client ! timed out waiting for pong
DEBUG:websockets.protocol:client ! failing OPEN WebSocket connection with code 1011
DEBUG:websockets.protocol:client - state = CLOSING
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=<Opcode.CLOSE: 8>, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
DEBUG:root:no message in 10 seconds
DEBUG:websockets.protocol:client ! timed out waiting for TCP close
DEBUG:websockets.protocol:client x closing TCP connection
DEBUG:websockets.protocol:client - event = connection_lost([SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2745))
DEBUG:websockets.protocol:client - state = CLOSED
DEBUG:websockets.protocol:client x code = 1006, reason = [no reason]
DEBUG:websockets.protocol:client - aborted pending ping: 337b5154
DEBUG:root:connection closed code = 1006 (connection closed abnormally [internal]), no reason
DEBUG:root:ignore message WSListenerState.STREAMING
DEBUG:root:connection closed code = 1006 (connection closed abnormally [internal]), no reason
DEBUG:root:ignore message WSListenerState.STREAMING
DEBUG:root:connection closed code = 1006 (connection closed abnormally [internal]), no reason
DEBUG:root:ignore message WSListenerState.STREAMING
DEBUG:root:connection closed code = 1006 (connection closed abnormally [internal]), no reason
DEBUG:root:ignore message WSListenerState.STREAMING
DEBUG:root:connection closed code = 1006 (connection closed abnormally [internal]), no reason
DEBUG:root:ignore message WSListenerState.STREAMING
(...)
```
Tested with v.1.0.10.
The "code = 1006" are a lot and show up after a while, the cable is still disconnected.

**Comment by motumboe** [comment]
This program does solve the issue:
https://gist.github.com/pgrandinetti/964747a9f2464e576b8c6725da12c1eb
 
```
import socket
import asyncio
import websockets
import time
import logging
import argparse
import threading
import sys


logger = logging.getLogger(__name__)

logging.basicConfig(
    stream=sys.stdout,
    level=logging.DEBUG,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)


class WSClient():

    def __init__(self, url, **kwargs):
        self.url = url
        # set some default values
        self.reply_timeout = kwargs.get('reply_timeout') or 10
        self.ping_timeout = kwargs.get('ping_timeout') or 5
        self.sleep_time = kwargs.get('sleep_time') or 5
        self.callback = kwargs.get('callback')


    async def listen_forever(self):
        while True:
        # outer loop restarted every time the connection fails
            logger.debug('Creating new connection...')
            try:
                async with websockets.connect(self.url) as ws:
                    while True:
                    # listener loop
                        try:
                            reply = await asyncio.wait_for(ws.recv(), timeout=self.reply_timeout)
                        except (asyncio.TimeoutError, websockets.exceptions.ConnectionClosed):
                            try:
                                pong = await ws.ping()
                                await asyncio.wait_for(pong, timeout=self.ping_timeout)
                                logger.debug('Ping OK, keeping connection alive...')
                                continue
                            except:
                                logger.debug(
                                    'Ping error - retrying connection in {} sec (Ctrl-C to quit)'.format(self.sleep_time))
                                await asyncio.sleep(self.sleep_time)
                                break
                        logger.debug('Server said > {}'.format(reply))
                        if self.callback:
                            self.callback(reply)
            except socket.gaierror:
                logger.debug(
                    'Socket error - retrying connection in {} sec (Ctrl-C to quit)'.format(self.sleep_time))
                await asyncio.sleep(self.sleep_time)
                continue
            except ConnectionRefusedError:
                logger.debug('Nobody seems to listen to this endpoint. Please check the URL.')
                logger.debug('Retrying connection in {} sec (Ctrl-C to quit)'.format(self.sleep_time))
                await asyncio.sleep(self.sleep_time)
                continue


def start_ws_client(client):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(client.listen_forever())


def callback_fn(data, *args, **kwargs):
    # Write here your logic
    logger.debug('This is the callback speaking!') # ignore data


if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('--url',
                        required=False,
                        # set here your URL
                        default='ws://katiedj.com:8080/macro/sample/',
                        dest='url',
                        help='Websocket URL')

    parser.add_argument('--reply-timeout',
                        required=False,
                        dest='reply_timeout',
                        type=int,
                        help='Timeout for reply from server')

    parser.add_argument('--ping-timeout',
                        required=False,
                        dest='ping_timeout',
                        default=None,
                        help='Timeout when pinging the server')

    parser.add_argument('--sleep',
                        required=False,
                        type=int,
                        dest='sleep_time',
                        default=None,
                        help='Sleep time before retrieving connection')

    args = parser.parse_args()

    ws_client = WSClient(**vars(args), callback=callback_fn)
    start_ws_client(ws_client)

```
Call it with e.g.
`$ python3 automatic_websocket_reconnect.py --url wss://stream.binance.com:9443/ws/btcusdt@aggTrade
`

See also
https://github.com/aaugustin/websockets/issues/414

Sorry but I am not able to spot the difference with your code.
