### ISSUE TITLE
get_fixed_activity_project_list not working

### ISSUE THREAD

**Issue by cristipurdel** [sammchardy/python-binance#837]
**Describe the bug**
I am trying to get https://binance-docs.github.io/apidocs/spot/en/#get-fixed-and-activity-project-list-user_data
via client.get_fixed_activity_project_list

**To Reproduce**

asset = ""
type = "ACTIVITY"
status = ""
isSortAsc = ""
sortBy = ""
current = ""
size = ""
recvWindow = 10
timestamp = 10
client.get_fixed_activity_project_list(type, timestamp)

**Expected behavior**
I would like to get the info for staking(fixed) and activity 

**Environment (please complete the following information):**
 - Python version: [e.g. 3.7.4]
 - Virtual Env: [miniconda]
 - OS: [Windows]
 - python-binance version 1.0.7

**Logs or Additional context**

Traceback (most recent call last):
  File "_test.py", line 27, in <module>
    client.get_fixed_activity_project_list(type, timestamp)
TypeError: get_fixed_activity_project_list() takes 1 positional argument but 3 were given

**Comment by sammchardy** [comment]
You will need to name the parameters

The timestamp is not necessary as the API library handles that for you.

`client.get_fixed_activity_project_list(type=type)`

**Comment by cristipurdel** [comment]
> You will need to name the parameters
> 
> The timestamp is not necessary as the API library handles that for you.
> 
> `client.get_fixed_activity_project_list(type=type)`

I tried it and I am getting different error

`Traceback (most recent call last):
  File "_test.py", line 29, in <module>
    client.get_fixed_activity_project_list(type=type)
  File "D:\Kit\PortableApps\Miniconda_small_binance\lib\site-packages\binance\client.py", line 4118, in get_fixed_activity_project_list
    return self._request_margin_api('get', 'lending/project/list', signed=True, data=params)
  File "D:\Kit\PortableApps\Miniconda_small_binance\lib\site-packages\binance\client.py", line 358, in _request_margin_api
    return self._request(method, uri, signed, **kwargs)
  File "D:\Kit\PortableApps\Miniconda_small_binance\lib\site-packages\binance\client.py", line 309, in _request
    return self._handle_response(self.response)
  File "D:\Kit\PortableApps\Miniconda_small_binance\lib\site-packages\binance\client.py", line 318, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.`
