### ISSUE TITLE
Lost response when existing ipython

### ISSUE THREAD

**Issue by willguxy** [sammchardy/python-binance#84]
Doesn't look significant but just want to point out in case it indicate other potential caveats. Got the following error after entering `exit` from ipython.

```
Exception ignored in: <module 'threading' from '/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

Previously did `bm.start()`, `bm.close()` to test out the socket api.

**Comment by willguxy** [comment]
[I found the answer to my own question](http://python-binance.readthedocs.io/en/latest/websockets.html#close-and-exit-program)

Closing for now.
