### ISSUE TITLE
symbol_book_ticker_socket() got an unexpected keyword argument 'streams'

### ISSUE THREAD

**Issue by NeroNekro** [sammchardy/python-binance#845]
Hello there,

i want to start multiple streams with:
`twm = ThreadedWebsocketManager(api_key=tradingBot.Broker.APIKEY, api_secret=tradingBot.Broker.SECRET)
        twm.start()
        streams = ['btceur@aggTrade', 'etheur@aggTrade', "bcheur@aggTrade",  "xrpeur@aggTrade",
                    "btceur@kline_1m", 'etheur@kline_1m', "bcheur@kline_1m",  "xrpeur@kline_1m"]
        twm.start_multiplex_socket(callback=self.process_m_message, streams=streams)`

and get the following:
`Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\Tobi\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Tobi\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Tobi\PycharmProjects\BitcoinTrader\Module\trader.py", line 238, in get_stockdata
    twm.start_multiplex_socket(callback=self.process_m_message, streams=streams)
  File "C:\Users\Tobi\PycharmProjects\BitcoinTrader\venvWIN\lib\site-packages\binance\streams.py", line 1212, in start_multiplex_socket
    'streams': streams
  File "C:\Users\Tobi\PycharmProjects\BitcoinTrader\venvWIN\lib\site-packages\binance\streams.py", line 1039, in _start_async_socket
    socket = getattr(self._bsm, socket_name)(**params)
TypeError: symbol_book_ticker_socket() got an unexpected keyword argument 'streams'`

The Code example is form the documentation. Is it a bug in the library or in my code?

**Comment by AlexNik** [comment]
@NeroNekro which version of  `python-binance` do you use?

**Comment by NeroNekro** [comment]
> @NeroNekro which version of `python-binance` do you use?

I use the verison 1.0.8

**Comment by sammchardy** [comment]
This is now fixed in v1.0.9 thanks to #844

**Comment by NeroNekro** [comment]
thanks for the quick fix

**Comment by NeroNekro** [comment]
I had tested the new version and @kline_1m works fine, but for @aggTrade I dont get any data.
