### ISSUE TITLE
AsyncClient.create() fails: unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by hhatefi** [sammchardy/python-binance#867]
Hi
I run a simple async code to get the exchange info:

```
async def main():
    api_key = 'my api code'                            
    api_secret = 'my api secret'                         
    client = await AsyncClient.create(api_key, api_secret)                                                 
    exchange_info = await client.get_exchange_info()                                                      
if __name__ == "__main__": 
    loop = asyncio.get_event_loop()                                                                       
    loop.run_until_complete(main())      
```
While creating a simple async client, I get the following error:

```
Exception ignored in: <function ClientSession.__del__ at 0x7f8bc7f1eb00>
Traceback (most recent call last):
  File "/home/user/lib64/anaconda3/envs/binance/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py", line 269, in __del__
    if not self.closed:
  File "/home/user/lib64/anaconda3/envs/binance/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py", line 894, in closed
    return self._connector is None or self._connector.closed
AttributeError: _connector
Traceback (most recent call last):
  File "run_algo.py", line 55, in <module>
    loop.run_until_complete(main())
  File "/home/user/lib64/anaconda3/envs/binance/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "run_algo.py", line 49, in main
    client = await AsyncClient.create(api_key,api_secret)
  File "/home/user/lib64/anaconda3/envs/binance/lib/python3.7/site-packages/python_binance-1.0.10-py3.7.egg/binance/client.py", line 6445, in create
  File "/home/user/lib64/anaconda3/envs/binance/lib/python3.7/site-packages/python_binance-1.0.10-py3.7.egg/binance/client.py", line 6436, in __init__
  File "/home/user/lib64/anaconda3/envs/binance/lib/python3.7/site-packages/python_binance-1.0.10-py3.7.egg/binance/client.py", line 154, in __init__
  File "/home/user/lib64/anaconda3/envs/binance/lib/python3.7/site-packages/python_binance-1.0.10-py3.7.egg/binance/client.py", line 6459, in _init_session
TypeError: __init__() got an unexpected keyword argument 'loop'
```

### Environment
 - Python version: 3.7.10
 - Virtual Env: conda
 - OS: Arch Linux
 - python-binance: v1.0.10

**Comment by hhatefi** [comment]
The problem seems to be inconsistency between packages in my venv. After creating a fresh venv with python 3.7 and installing `python-binance`, the problem was fixed.
