### ISSUE TITLE
simplejson.scanner.JSONDecodeError

### ISSUE THREAD

**Issue by echel0n** [sammchardy/python-binance#90]
Traceback (most recent call last):
  File "trader.py", line 612, in <module>
    main()
  File "trader.py", line 600, in main
    bt.action(client.get_order_book(symbol=option.market.upper() + option.funding.upper()))
  File "/usr/local/lib/python2.7/dist-packages/binance/client.py", line 449, in get_order_book
    return self._get('depth', data=params)
  File "/usr/local/lib/python2.7/dist-packages/binance/client.py", line 180, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/binance/client.py", line 154, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/binance/client.py", line 149, in _request
    return self._handle_response(response)
  File "/usr/local/lib/python2.7/dist-packages/binance/client.py", line 173, in _handle_response
    raise BinanceAPIException(response)
  File "/usr/local/lib/python2.7/dist-packages/binance/exceptions.py", line 10, in __init__
    json_res = response.json()
  File "/root/.local/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by echel0n** [comment]
This error is very random so not sure if its tied to the connection timing out but I don't see any indication of it

**Comment by sammchardy** [comment]
Hi @echel0n, yes ok I see how that could happen, trying to parse an error response to JSON.

I'll add some error checking in there to handle that case.

**Comment by sammchardy** [comment]
Hi @echel0n I've released v0.6.2 with some better handling for this case.
