### ISSUE TITLE
Websocket to track real-time price of Bitcoin  

### ISSUE THREAD

**Issue by tifDev** [sammchardy/python-binance#936]
Hi,

How can I use the websocket to track the real-time price of Bitcoin pls?

**Environment (please complete the following information):**
 - Python version: 3.6.9
 - OS: Ubuntu

Thank you

**Comment by pennymax** [comment]
# create ws manager
    twm = ThreadedWebsocketManager(api_key=api_key, api_secret=api_secret, tld='com')
    
    # start
    twm.start() 

    def handle_socket_symbol_ticker(msg):
        price = msg['c']
    
    # start socket for single symbol ticker price 
    twm.start_symbol_ticker_socket(callback=handle_socket_symbol_ticker, symbol='BTCUSDT')

**Comment by tifDev** [comment]
Hi,

I'm getting an error:

```
>>> # start socket for single symbol ticker price
... twm.start_symbol_ticker_socket(callback=handle_socket_symbol_ticker,
...                                symbol='BTCUSDT')
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/webt/.local/lib/python3.6/site-packages/binance/streams.py", line 1175, in start_symbol_ticker_socket
    'symbol': symbol,
  File "/home/webt/.local/lib/python3.6/site-packages/binance/streams.py", line 1096, in _start_async_socket
    self._loop.call_soon_threadsafe(asyncio.create_task, self.start_listener(socket, socket._path, callback))
AttributeError: module 'asyncio' has no attribute 'create_task'
```

This is the code executed:

```
import os, asyncio
from binance.client import Client
from binance.streams import BinanceSocketManager, ThreadedWebsocketManager  # noqa

# init
api_key = 'xxx'
api_secret = 'xxx'

twm = ThreadedWebsocketManager(api_key=api_key,
                               api_secret=api_secret,
                               tld='com')

# start
twm.start()

def handle_socket_symbol_ticker(msg):
    price = msg['c']

# start socket for single symbol ticker price
twm.start_symbol_ticker_socket(callback=handle_socket_symbol_ticker,
                               symbol='BTCUSDT')

```

Can you pls assist?

Thank you

**Comment by tifDev** [comment]
Hi, 

Any update?

Thanks

**Comment by jlixfeld** [comment]
Have a look here: https://sammchardy.github.io/async-binance-basics/

**Comment by tifDev** [comment]
> @tifDev had the same issue, in my case it was python version 3.6. Version 3.7 fixed it.

I installed version 3.7 but seems that is not recognizing the python-binance module installed:

```

 python3.7
Python 3.7.5 (default, Feb 23 2021, 13:22:40) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, asyncio
>>> from binance.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'binance'
>>> from binance.streams import BinanceSocketManager, ThreadedWebsocketManager  # noqa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'binance'

```

Thank you

**Comment by tifDev** [comment]
> @tifDev had the same issue, in my case it was python version 3.6. Version 3.7 fixed it.

Thanks bro, the whole code is working. But I expected to have something displaying the value "live" :
```

>>> # start socket for single symbol ticker price
... twm.start_symbol_ticker_socket(callback=handle_socket_symbol_ticker,
...                                symbol='BTCUSDT')
'btcusdt@ticker'
>>> 

```

**Comment by tifDev** [comment]
I found what I was looking for to pull the live price via websocket:

```

import websocket, json
cc = 'btceur'
interval = '1m'
socket_kline = f'wss://stream.binance.com:9443/ws/{cc}t@kline_{interval}'
socket_aggTrade = f'wss://stream.binance.com:9443/ws/{cc}t@aggTrade'


def on_message(ws, message):
  print(message)


def on_close(ws):
  print("Connection closed")


ws_kline = websocket.WebSocketApp(socket_kline,on_message = on_message, on_close = on_close)
ws_aggTrade = websocket.WebSocketApp(socket_aggTrade,on_message = on_message, on_close = on_close)


ws_kline.run_forever()
ws_aggTrade.run_forever()

```
