### ISSUE TITLE
APIError(code=0): Invalid JSON error message from Binance:

### ISSUE THREAD

**Issue by countblackjack** [sammchardy/python-binance#963]
Note that this is my first python program and my first post on github. The code used to work fine, all of the sudden it doesnt work anymore. It could be due to the things that are going on with binance and options, just want to make sure that it is not something I overlooked. 

Code used to run fine, now suddenly returns " APIError(code=0): Invalid JSON error message from Binance:" 

**To Reproduce**
```
from binance.client import Client
from binance.exceptions import BinanceAPIException

import bin_config

client = Client(bin_config.apikey, bin_config.apiSecurity)

OptionsInfo = client.options_info()
for s in OptionsInfo['data']:
                instrument_name = client.options_order_book(symbol=s['symbol'])
                #print(s['symbol'])

```
**Expected behavior**
Should return order book 

**Environment (please complete the following information):**
 - Python version: [e.g. 3.5]: 3.7.4
 - Virtual Env: [e.g. virtualenv, conda]: 
 - OS: Windows
 - python-binance version: (1.0.12)

**Logs or Additional context**
binance.exceptions.BinanceAPIException: APIError(code=0): Invalid JSON error message from Binance: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="format-detection" content="telephone=no,email=no,address=no" />
    <script src="https://bin.bnbstatic.com/static/sensors/sensorsdata@1.15.1.min.js"></script>
    <title>Binance</title>
    <link rel="shortcut icon" type="image/x-icon" href="https://bin.bnbstatic.com/static/images/common/favicon.ico">
    <style>
      html,
      body {
        font-family: BinancePlex, Arial, PingFangSC-Regular, "Microsoft YaHei",
          sans-serif;
      }
      body {
        margin: 0;
      }
      .not-fount-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        flex-direction: column;
        background: #fafafa;
      }
      .not-fount-image {
        width: 400px;
      }
      .not-fount-tips {
        margin-top: 16px;
        display: flex;
        align-items: center;
      }
      .not-fount-tips-bold {
        font-size: 24px;
        line-height: 28px;
        color: #1e2026;
        font-weight: 500;
      }
      .link {
        color: #d0980b;
        font-size: 14px;
        line-height: 20px;
      }

      img {
        width: 100%;
        display: block;
      }
      .not-found-board-logo {
        width: 56px;
      }
      .not-found-board-left {
        display: flex;
      }
      .not-found-board-text {
        margin-left: 16px;
        color: #1e2026;
        font-weight: bold;
        margin-top: 6px;
        font-size: 16px;
      }
      .not-found-board-text-inner {
        display: flex;
      }
      .text-inner-icons {
        margin-left: 16px;
        display: flex;
        align-items: center;
      }
      .text-inner-icons span {
        display: inline-block;
        width: 16px;
        height: 16px;
        margin-right: 10px;
        background-position: center;
        background-repeat: no-repeat;
      }
      .icon-mac {
        background-image: url("https://bin.bnbstatic.com/static/images/electron/macicon.svg");
      }
      .icon-linux {
        background-image: url("https://bin.bnbstatic.com/static/images/electron/linux.svg");
      }
      .icon-windows {
        background-image: url("https://bin.bnbstatic.com/static/images/electron/windows.svg");
      }
      .not-found-board-right {
        margin-top: 6px;
      }
      button {
        padding: 10px 16px;
        border: none;
        outline: none;
        background: linear-gradient(180deg, #f8d12f 0%, #f0b90b 100%);
        border-radius: 4px;
        cursor: pointer;
        font-size: 14px;
        color: #1e2026;
        font-weight: 500;
      }
      @media only screen and (max-device-width: 1024px) {
        .not-found-board {
          display: none;
        }
      }
      @media only screen and (min-device-width: 1025px) {
        .not-found-board {
          background: #ffffff;
          padding: 0 16px;
          height: 80px;
          box-shadow: 0px 0px 1px rgba(20, 21, 26, 0.1),
            0px 3px 6px rgba(71, 77, 87, 0.04),
            0px 1px 2px rgba(20, 21, 26, 0.04);
          border-radius: 4px;
          width: 496px;
          margin-top: 56px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
      }
    </style>
  </head>
  <body>
    <div class="not-fount-container">
      <div class="not-fount-image">
        <img
          width="100%"
          src="https://bin.bnbstatic.com/static/images/electron/500.png"
          alt=""
        />
      </div>
      <div class="not-fount-tips">
        <span class="not-fount-tips-bold"
          >Weâre sorry, but something went wrong.</span
        >
        <span style="margin-left: 16px"
          ><a href="/" class="link"
            >Go to Homepage</a
          ></span
        >
      </div>
      <div class="not-found-board">
        <div class="not-found-board-left">
          <div class="not-found-board-logo">
            <img
              src="https://bin.bnbstatic.com/static/images/electron/logo_01.png"
              alt=""
            />
          </div>
          <div class="not-found-board-text">
            <div class="not-found-board-text-inner">
              <div>Binance desktop</div>
              <div class="text-inner-icons">
                <span class="icon-windows"></span>
                <span class="icon-linux"></span>
                <span class="icon-mac"></span>
              </div>
            </div>
            <div
              style="
                font-size: 14px;
                color: #474d57;
                font-weight: 400;
                margin-top: 6px;
              "
            >
              A secure, fast and smooth trading experience.
            </div>
          </div>
        </div>
        <div class="not-found-board-right">
          <button id="njewuisj-500-desktop-download">Download Now</button>
        </div>
      </div>
    </div>
    <script>
      window.sensors = window["sensorsDataAnalytic201505"];
      if (sensors) {
        sensors.init({
          show_log: false,
          name: "sensors",
          server_url: "https://sensors.binance.cloud/sa?project=binance",
          heatmap: {
            // collect_elements: "all",
          },
          heatmap_url:
            "https://bin.bnbstatic.com/static/sensorsdata/heatmap.min.js",
          batch_send: false,
          send_type: "beacon",
          callback_timeout: 2000,
        });
        sensors.quick("autoTrack", {
          canary: "beta",
        });
      }
      window.onload = function () {
        var downloadBtn = document.getElementById(
          "njewuisj-500-desktop-download"
        );

        var p = navigator.platform;
        var isMac = p.indexOf("Mac") == 0;
        var isWin = p.indexOf("Win") == 0;
        var isLinux = p == "X11" || p.indexOf("Linux") == 0;
        downloadBtn.addEventListener("click", function () {
          if (isMac) {
            window.location.href =
              "https://ftp.binance.com/electron-desktop/mac/production/binance.dmg";
          }
          if (isWin) {
            window.location.href =
              "https://ftp.binance.com/electron-desktop/windows/production/binance-setup.exe";
          }
          if (isLinux) {
            window.location.href =
              "https://ftp.binance.com/electron-desktop/linux/production/binance-x86_64-linux.rpm";
          }
        });
      };
    </script>
  </body>
</html>

**Comment by Karlheinzniebuhr** [comment]
I'm getting this error when sending
```
params={
        'symbol': SYMBOL_TO_TRADE,
        'side': tp_sl_side,
        'quantity': str(quantity),
        'price': str(tp_price),
        'stopPrice': str(tp_stop_price),
        'stopLimitPrice': str(sl_price),
        'stopLimitTimeInForce':'GTC',
        'isIsolated': isIsolated,
        'sideEffectType': 'MARGIN_BUY'
        }

oco_order = cls.client._post('margin/order/oco', True, data=params)
```

Did you find a solution?

**Comment by harsh-sangwan** [comment]
Traceback (most recent call last):
  File "/Users/harshdeep.sangwan/PycharmProjects/pythonProject1/binance futures.py", line 264, in <module>
    y = client.futures_position_information(symbol=symbol)
  File "/opt/anaconda3/lib/python3.9/site-packages/binance/client.py", line 5417, in futures_position_information
    return self._request_futures_api('get', 'positionRisk', True, data=params)
  File "/opt/anaconda3/lib/python3.9/site-packages/binance/client.py", line 339, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/binance/client.py", line 315, in _request
    return self._handle_response(self.response)
  File "/opt/anaconda3/lib/python3.9/site-packages/binance/client.py", line 324, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=0): Invalid JSON error message from Binance: <!DOCTYPE html>

<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="format-detection" content="telephone=no,email=no,address=no">
  <title>Binance</title>
  <link rel="Shortcut Icon" href="https://www.binance.com/en/favicon.ico">
  <style>
    body {
      margin: 0
    }

    .img {
      width: 611px;
      margin: 68px auto 0
    }

    .info {
      width: 370px;
      margin: 0 auto;
      text-align: center;
      font-family: Arial;
    }

    .info h3 {
      margin: 0;
      font-size: 25px;
      color: #333;
      font-weight: normal;
    }

    .info p {
      font-size: 14px;
      font-family: Arial;
      color: #333;
      line-height: 18px;
      margin: 0
    }

    .info button {
      margin-top: 20px;
      width: 231px;
      height: 34px;
      background: #FFFFFF;
      border: 1px solid #F0B90B;
      box-sizing: border-box;
      border-radius: 3px;
      font-size: 14px;
      line-height: 16px;
      color: #F0B90B;
    }
  </style>
</head>

<body>
  <div class="img"><img alt="" src="/errorPages/404.jpg"></div>
  <div class="info">
    <h3>åºéå¦ï¼æ¨è®¿é®çç½é¡µä¸å­å¨ã</h3>
    <p>Sorry! The page youâre looking for cannot be found.</p>
    <a href="https://www.binance.com">
      <button>Return to Binance home page</button>
    </a>
  </div>

</body>

</html>

I'm getting this error

**Comment by Acutapugione** [comment]
.venv/lib/python3.10/site-packages/binance/client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=0): Invalid JSON error message from Binance: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
