### ISSUE TITLE
get_historical_klines generates time zone error

### ISSUE THREAD

**Issue by dr1ver1** [sammchardy/python-binance#965]
Calling get_historical_klines raises an error related to timezone / tzdata
**To reproduce:**
`candles = client.get_historical_klines(symbol='BTCUSDT', interval=Client.KLINE_INTERVAL_1DAY, start_str='1 Jan, 2021')`
I've tried various formats for the date, with no success.

**Error**: ...line 27, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
backports.zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Europe/London'

**Expected behaviour:**
The following code works as expected:
`candles = client.get_klines(symbol=symbol, interval=Client.KLINE_INTERVAL_1DAY)`
I have created an environment purely for this project.

**Environment:**
 - Python version: Python 3.7.10
 - Virtual Env: conda 4.10.3
 - OS: Windows 10 Home 64-bit
 - python-binance version 1.0.12

**Full error:**
Traceback (most recent call last):
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\backports.zoneinfo-0.2.1-py3.7-win-amd64.egg\backports\zoneinfo\_common.py", line 15, in load_tzdata
    return importlib_resources.open_binary(package_name, resource_name)
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\importlib\resources.py", line 88, in open_binary
    package = _get_package(package)
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\importlib\resources.py", line 47, in _get_package
    module = import_module(package)
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/David/OneDrive/PycharmProjects/TradingData/get_data.py", line 35, in <module>
    candles = client.get_historical_klines(symbol=symbol, interval=Client.KLINE_INTERVAL_1DAY, start_str='1 Jan, 2021')
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\python_binance-1.0.12-py3.7.egg\binance\client.py", line 932, in get_historical_klines
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\python_binance-1.0.12-py3.7.egg\binance\client.py", line 966, in _historical_klines
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\python_binance-1.0.12-py3.7.egg\binance\helpers.py", line 72, in convert_ts_str
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\python_binance-1.0.12-py3.7.egg\binance\helpers.py", line 23, in date_to_milliseconds
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\dateparser-1.0.0-py3.7.egg\dateparser\conf.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\dateparser-1.0.0-py3.7.egg\dateparser\__init__.py", line 54, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\dateparser-1.0.0-py3.7.egg\dateparser\date.py", line 422, in get_date_data
    locale, date_string, date_formats, settings=self._settings)
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\dateparser-1.0.0-py3.7.egg\dateparser\date.py", line 178, in parse
    return instance._parse()
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\dateparser-1.0.0-py3.7.egg\dateparser\date.py", line 182, in _parse
    date_data = self._parsers[parser_name]()
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\dateparser-1.0.0-py3.7.egg\dateparser\date.py", line 196, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\dateparser-1.0.0-py3.7.egg\dateparser\freshness_date_parser.py", line 159, in get_date_data
    date, period = self.parse(date_string, settings)
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\dateparser-1.0.0-py3.7.egg\dateparser\freshness_date_parser.py", line 95, in parse
    self.now = datetime.now(self.get_local_tz())
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\dateparser-1.0.0-py3.7.egg\dateparser\freshness_date_parser.py", line 43, in get_local_tz
    return get_localzone()
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\tzlocal-3.0b1-py3.7.egg\tzlocal\win32.py", line 98, in get_localzone
  File "C:\Users\David\Anaconda3\envs\TradingData\lib\site-packages\backports.zoneinfo-0.2.1-py3.7-win-amd64.egg\backports\zoneinfo\_common.py", line 27, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
backports.zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Europe/London'

Process finished with exit code 1

**Comment by dr1ver1** [comment]
I've resolved it / found a workaround by creating a new project and using venv instead of conda. I also had issues when installing the package under conda
