### ISSUE TITLE
ERROR: Task exception was never retrieved

### ISSUE THREAD

**Issue by paul2225** [sammchardy/python-binance#997]
Hello @sammchardy! Ticker socket throws this sometimes. Do you have any idea why this error could happen? 

2021-08-25 11:34:59,986 ERROR: Task exception was never retrieved
future: <Task finished name='Task-47792629' coro=<KeepAliveWebsocket._keepalive_socket() done, defined at binance/streams.py:246> exception=TimeoutError()>
Traceback (most recent call last):
  File "binance/streams.py", line 247, in _keepalive_socket
  File "binance/streams.py", line 234, in _get_listen_key
  File "binance/client.py", line 7026, in stream_get_listen_key
  File "binance/client.py", line 6554, in _post
  File "binance/client.py", line 6514, in _request_api
  File "binance/client.py", line 6495, in _request
  File "aiohttp/client.py", line 1117, in aenter
  File "aiohttp/client.py", line 544, in _request
  File "aiohttp/client_reqrep.py", line 905, in start
  File "aiohttp/helpers.py", line 656, in exit
asyncio.exceptions.TimeoutError

**Comment by PabloBorda** [comment]
Hello I confirm that I am facing the same problem, any ideas ?
